### ISSUE TITLE
Can't edit instructions

### ISSUE THREAD

**Issue by jimbolaya** [mrzapp/nextcloud-cookbook#1]
Thank you for making this available. It looks cool and looks like it can have a lot of potential.

I tried downloading a recipe here:
https://www.verywellfit.com/spelt-bread-recipe-for-a-bread-machine-2506888
and it didn't import at all, but the page had a "print" option, so I tried that:
https://www.verywellfit.com/spelt-bread-recipe-for-a-bread-machine-2506888?print
and I was able to get the Ingredients in, but no Instructions showed up.

When I edited the recipe, I assume I should add the Instructions by clicking on the "+". But I don't seem to get an edit box or anything like that.  

Clicking on "Save" also doesn't seem to do anything, but it did seem to do something since already filled in fields did save changes, but check boxes in the "Daily Dozen" didn't.

I should probably go back and read any release notes.

**Comment by christianlupus** [comment]
I can confirm this behavior. The browser console shows no errors as far as I see.

**Comment by mrzapp** [comment]
Huh, that website does seem to use the correctly formatted schema.org JSON. I don't have much time to work on this currently, though.

If you're interested in helping out, [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L387) would be the place to start debugging this.

**Comment by mrzapp** [comment]
Ok, after looking more thoroughly at their markup, they messed it up quite bad. This is their instructions string:

```
"recipeInstructions": "&lt;ol&gt;&lt;li&gt;Pour water into bread machine loaf pan. Next, add salt, canola oil, and honey.&lt;/li&gt;&lt;li&gt;Add the flour, in a mound shape, so some of it sticks up above the water (this is especially important if you set your bread machine to start later in the day — you want to keep the yeast away from the water until the dough begins to mix).&lt;/li&gt;&lt;li&gt;With a spoon, make a small well in the center of the mound, and then pour the yeast into that well.&lt;/li&gt;&lt;li&gt;Set bread maker to 1 1/2 pound loaf (basic setting) with a medium crust or see your manufacturer&amp;#39;s instruction manual.&lt;/li&gt;&lt;/ol&gt;"
```

They've encoded HTML entities instead of removing them. I'll try to circumvent that somehow.

**Comment by mrzapp** [comment]
I've managed to fix most of this issue, but I can't reproduce the text box not showing up when you click the + button. Which browser/OS are you on?

**Comment by poltrian** [comment]
There is no + Button. I use Firefox

Jeppe Zapp <notifications@github.com> schrieb am Di., 28. Mai 2019, 11:53:

**Comment by poltrian** [comment]
Tryed it out with chrome. same not + Button. But the page https://www.kochbar.de/rezept/536907/Biggi-s-Dessert-EIS-Vanille-mit-Obst-und-Caramel.html will work with Ingredients and Instructions, but also can't edit

**Comment by mrzapp** [comment]
I'm on Firefox too, can you take a screenshot of the page you're talking about? This is what I'm seeing:

![image](https://user-images.githubusercontent.com/2747428/58470533-2d56d200-8142-11e9-92b3-eecf068b5a50.png)

**Comment by poltrian** [comment]
![grafik](https://user-images.githubusercontent.com/50879520/58470879-ee754c00-8142-11e9-8daa-1f8a4424f0e9.png)

**Comment by mrzapp** [comment]
You need to click the edit icon next to the recipe in the list

**Comment by poltrian** [comment]
ohhh ok i see, now i works. But recipes from Chefkoch.de or lecker.de missing the instruction.
https://www.lecker.de/omas-hackbraten-35095.html
or
https://www.chefkoch.de/rezepte/643101165400472/Ofenkartoffeln-mit-Pfifferlingen.html
or
https://www.rewe.de/rezepte/bier-frikadellen-burger-pilz-zwiebel-geroestl/

is there solutions possible? Would be great. I'm happy with your cookbook

**Comment by christianlupus** [comment]
I think the original problem still persists, so please reopen this issue.

To reproduce you need to prepare:

- Take any recipe (I tried with https://www.chefkoch.de/rezepte/643101165400472/Ofenkartoffeln-mit-Pfifferlingen.html).
- Add it to the list of recipes. There are some instructions added.
- Edit the recipe manually and remove all blocks of instructions. Save it.

After this, if you open edit again, there is no textarea in the lower page part to insert instructions. Adding new ones is not working as well using the "+" sign.
I do not see any JS errors or network traffic but I might have overseen something.

**Comment by jimbolaya** [comment]
Here's what I see when I attempt to edit a recipe with no instructions.

![cookbook no edit box](https://user-images.githubusercontent.com/3241087/58481745-04771280-812b-11e9-9597-4031de51a399.png)

I thought clicking on the "+" below "Instructions" would open another box for me to add text to.

**Comment by mrzapp** [comment]
Ah, I see. Sorry, this issue was actually 3 issues, so it got a bit confusing

**Comment by mrzapp** [comment]
@poltrian I just tested the links you provided, and they work just fine. I'm uploading a new release v0.1.3 now

**Comment by christianlupus** [comment]
@mrzapp I think you solved the problem. Thank you very much for your quick solution! :+1:

**Comment by mrzapp** [comment]
@christianlupus no worries :)
