### ISSUE TITLE
"Search" and the "Tag Selector" dropdowns are a bit confusing.

### ISSUE THREAD

**Issue by dmbreakey** [mrzapp/nextcloud-cookbook#101]
My intuitive assumption when seeing these was that the "Search" box would allow me to search the entire recipe (eg: searching for "instant" would pull up any recipe no matter _where_ the term shows up, whether in the name, description, steps or even ingredients).

Meanwhile the tag selector, below, would let me select recipes that match a precise tag (or tags).

Instead, we have two search functions that do _essentially_ the same thing, which is a bit counter-intuitive.

I think the current tag selector should have the _behavior_ of the current search box, but retaining the _appearance_ of the selector (as that provides a visual reinforcement that we're only searching a specific metadata subset).

- ie: a drop-down that you can click on and type to refine the list of selectable tags; if the user hits "Enter" on a partially entered text, then it searches for that text in any available tag (so if I have two tags that contain the word, then _both_ tags will be matched and filtered on).
- If the user instead selects a specific tag from the refined list, then search for _just_ that tag, and _only_ in the tag metadata.

Importantly, the result set should match **only** on the tag metadata; while I do find the current behavior of matching on both the name and tags _useful_, it's a bit confusing as it doesn't match the visual metaphor, and it lessens the usefulness of tags somewhat.

The search box should be where the user can enter any arbitrary text and it will search the **entire** recipe, including descriptions, ingredients, tags, steps, etc.

**Comment by mrzapp** [comment]
@dmbreakey currently, the search is done via a keyword lookup in a database table, so I'm not sure how you would accomplish the search portion of your suggestion.

I agree the tag selector should work better with the search box. I'd recommend you try to create the user interaction you want first without changing the database schema, I'll be happy to test it with you.

**Comment by dmbreakey** [comment]
I'm happy to look into it, but not sure if my skillset is up to it. However, how do I improve if I don't challenge myself, right?

It sounds like the real search function would require a more comprehensive solution than is currently available, but I'm happy to look into that too.

**Comment by mrzapp** [comment]
@dmbreakey Exactly :) I suggest you let the search backend stay as it is for now and focus on the user experience. It's important to keep a tight focus when learning.

**Comment by dmbreakey** [comment]
By "look into that" I mean more out of curiosity for now. Refactoring a UI I think I can figure out, since there's already code there to reference. But I have basically zero clues right now how to implement a proper search framework. ;-)

**Comment by Teifun2** [comment]
Do we have any plan on how to achieve this? Or is it even decided that we change it?

Possible solutions i see:
- We could try and use the search field only for local jquery title search and use the drop down to narrow the selection by category.
- We could remove the search field and only work with a searchable drop down (something like [this](https://www.w3schools.com/howto/howto_js_filter_dropdown.asp))
- We could implement a database that mirrors the json data structure in a database. This would allow us to do full text search for every piece we would every like to, but it would also lead to a host of new challenges. (Most difficult / Long Term)

**Comment by mrzapp** [comment]
@Teifun2 it's not planned yet, as this is more of a UX issue than technical, and no definite solution has been proposed so far.

The entire browsing experience could be better for sure, I actually think relying on the side panel was a bad move, as we could create a much richer search experience using the main content area. This issue requires more planning and creative direction than I can afford to spend on it for now, so I've shelved it until I have the time.
