### ISSUE TITLE
Dropdown when clicking on the "Search" box is black text on a slightly lighter background

### ISSUE THREAD

**Issue by dmbreakey** [mrzapp/nextcloud-cookbook#102]
This exhibits different behavior depending on the browser.

In Chrome 78, after **one** click, I get black text on a slightly lighter background; very nearly unreadable, as can be seen below:
![Selection_354](https://user-images.githubusercontent.com/197063/68074420-684bda00-fd60-11e9-8827-9b96d822567f.png)

In Opera 64, when I _first_ click the "Search" box, the dropdown is black text on a white background--_beautifully_ readable.

If I click in the search box a second time, then it changes to black text on a dark background. Still more readable than in Chrome (the dark background is just light enough I can still read the text fairly easily). See below for the **second** click appearance in Opera:
![Selection_355](https://user-images.githubusercontent.com/197063/68074523-8c5beb00-fd61-11e9-9b39-daabae838a41.png)

Strangely, if I try the same thing in Chrome (click a second time), it appears the same thing happens; the background gets _slightly_ lighter.

I believe this is an issue with my browsers, but I haven't been able to isolate the relevant CSS yet.

I haven't seen this happen with anything else in NextCloud yet.

I don't know if this might be relevant, but I am using the _Theming_ module to customize the site colors; I also do have the _Custom CSS_ addon installed, but I haven't inserted any customized CSS yet. I have tried turning both modules off; it doesn't make any difference that I see.

**Comment by mrzapp** [comment]
@dmbreakey it's a `datalist` element, which as far as I know is near impossible to style, if not entirely. If your browser is not presenting it right, it's not something we can do anything about, I'm afraid.
