### ISSUE TITLE
since last update recipes are still in folder but no longer listed in app 

### ISSUE THREAD

**Issue by yeakley64** [mrzapp/nextcloud-cookbook#103]
since last update recipes are still in folder but no longer listed in app i can add new recipes and they show but all the ones i had in before won't show even after re scanning of folder i tried to move all to new folder but will not list

**Comment by mrzapp** [comment]
@yeakley64 Do you have any relevant log messages? You seem to be the only user with this issue so far

**Comment by yeakley64** [comment]
thank you for the response i think i got it all back up for some reason
when i did a upgrade from 16 to 16.01 all my items where listed but i could
not open them then i tried to add one and it add fine but the others would
not open- so i seen there was a update to 16.2 so i updated again and i had
same issue  so i removed all of them and had a backup of them pushed all
back up and now its working again - they all were in like a cache account
you could see them listed but none would open  i use ubuntu 18.04 server
thanks again for the response all is good again 😀

**Comment by yeakley64** [comment]
sorry it was upgraded to 16.06
