### ISSUE TITLE
Images stopped showing up

### ISSUE THREAD

**Issue by GideonWolfe** [mrzapp/nextcloud-cookbook#106]
I am viewing my recipe library, many of which have images associated with them.

Editing the recipe shows a valid URL which links to an image. Instead, the placeholder "no image" graphic is shown

**Comment by mrzapp** [comment]
@GideonWolfe is there anything relevant in your log when you see this behaviour?

**Comment by poltrian** [comment]
After the default image was introduced, I had the same problem. I saved
all the recipes again then the pictures were back


Am Montag, den 11.11.2019, 22:54 -0800 schrieb Jeppe Zapp:

**Comment by mrzapp** [comment]
Ah yes, the image is pulled as the recipe is saved to avoid overwriting local images unnecessarily. This is not really a bug, then, but rather an unfortunate upgrade step between certain version numbers.

@GideonWolfe if you do as @poltrian this shouldn't happen again

**Comment by GideonWolfe** [comment]
@mrzapp Great, saving them again worked. Hopefully it won't happen again because manually saving my 100+ recipes was extremely tedious

**Comment by mrzapp** [comment]
@GideonWolfe we will use auto migration in future releases, but this app is still in beta (hence the 0.*.* version number), so a few occational setbacks are to be expected for the users until ve reach v1.0.0
