### ISSUE TITLE
Hide Encoding of Time

### ISSUE THREAD

**Issue by Teifun2** [mrzapp/nextcloud-cookbook#111]
I think the encoding of the time according to the ISO standards should be hidden from the user.

Most users will not know what the "PT" in front of the time measurement means and will potentially remove it or at least be confused by it. Therefore i think we should parse it during edit and creation of Recipes.

We could also consider doing it with a [specific time field](https://www.w3schools.com/tags/att_input_type_time.asp).

**Comment by Teifun2** [comment]
Or something similar to this one here: https://github.com/koss-lebedev/bootstrap-duration-picker

**Comment by mrzapp** [comment]
@Teifun2 I support the standard `time` field, I would like to push the HTML5 input fields as well.

We just need to make sure that the ISO format is preserved, but I think it's already taken care of by the `RecipeService::checkRecipe` method.

**Comment by Teifun2** [comment]
@mrzapp Dont you think this will turn away many potential users? We could make it optional?

**Comment by mrzapp** [comment]
@Teifun2 perhaps I was being unclear.

In the proposed solution, we would be using a `time` input field, which assumes a `HH:MM` format. This format will then be parsed by the backend to be saved in the ISO format (since this is more generally machine readable). When rendering the field on the recipe page, it will be formatted as `HH:MM` again.

This is a UX improvement no matter how I look at it. Or am I missing something?

**Comment by mrzapp** [comment]
@Teifun2 come to think of it, #95 is relevant here. We should make sure to increment hours when minutes go above 60.

Could be something like this:  

```php
$overflow_hours = floor($minutes / $hours);
$hours += $overflow_hours;
$minutes -= $overflow_hours * 60;
```

The sanity check should probably go [here](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/lib/Service/RecipeService.php#L289) somewhere.

**Comment by Teifun2** [comment]
> In the proposed solution, we would be using a time input field, which assumes a HH:MM format.

Ahh i misunderstood you, i'm sorry! I totally agree that using html5 standards if possible is a better solution.

> @Teifun2 come to think of it, the sanity check should probably go here somewhere.

I need to look at the checkRecipe anyway, i havent looked at it yet.

**Comment by Teifun2** [comment]
@mrzapp I looked into the `time` html tag. But there is one major flaw. I cannot remove the AM/PM marker without some CSS  manipulation.  Also the if the browser chooses the country standard of AM/PM instead of 24 hour system the field can display maximum 12 Hours which might be to low for some very very very special recipes.
All in all, it seems that this html tag is not yet really implemented over all browsers in a consistent way and misses many functions. Therefore i would like to try something else for the time being.

**Comment by mrzapp** [comment]
@Teifun2 yeah, maybe 2 simple `number` inputs would be enough, one for hours and one for minutes?

**Comment by Teifun2** [comment]
@mrzapp Do we want to give room for days? Assuming that there exist recipes with fermentation steps they can easily take multiple days. Obviously its there is the question if it makes sense to add these days to `prepareTime` but we could allow it?

**Comment by mrzapp** [comment]
@Teifun2 I think the markup `HH:MM` is all we really need. Users can always write `72:00` if they need to.

**Comment by mrzapp** [comment]
This is will be pushed with 0.6.0
