### ISSUE TITLE
Invalid argument supplied for foreach() at /var/www/nextcloud/apps/cookbook/templates/content/recipe.php#53

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#118]
Invalid argument supplied for foreach() at /var/www/nextcloud/apps/cookbook/templates/content/recipe.php#53
Undefined index: tool at /var/www/nextcloud/apps/cookbook/templates/content/recipe.php#53

Since new update when opening different recipes.

**Comment by Teifun2** [comment]
Could you provide me with the json of one Recipe that does not work? I'm so far unable to reproduce this error.

**Comment by Teifun2** [comment]
The code referenced in this issue is a `foreach` over all `tools`. I first expected recipes to fail that have no tools defined, but at my end every possibility works. 
We could just wrap the `foreach` with an `is_array()` but i would like to now how this error comes to live.

**Comment by xsus95** [comment]
[penne.txt](https://github.com/mrzapp/nextcloud-cookbook/files/3935469/penne.txt)

Please find the receipt attached to this message. While working fine running the previous update there seem to be issues with the current one.

**Comment by Teifun2** [comment]
I'm still unable to reproduce this even with your provided recipe. 

Could you tell me more info about your server and your problem? 
I'm especially interested in your web server. Do you run nextcloud over an nginx or apache webserver?
When does the error appear? When editing / saving / loading the recipe?

If i would provide a test branch / would you be able to manually install the plugin?

**Comment by Teifun2** [comment]
While searching around, i'm getting the feeling that this is possibly a issue due to the difference between nginx and apache. I see many reports of similar issues where the people always run nginx servers. It could be that Apache can handle empty foreach variables while nginx cannot.

If you can confirm that your running nginx that would be awesome. Otherwise i would be very confused ^^

**Comment by Teifun2** [comment]
The code for Tools / Ingredients / Instructions is exactly the same. Have you ever created a recipe with no instructions or no ingredients? Does the same (slightly different) error appear?

**Comment by xsus95** [comment]
Hey, the Error occures while click in a recipe to load. I use a nextcloudpi instance, so i think Apache. The recipe ist imported from https://www.chefkoch.de/ like all receipts who wont Work. But i know that i dont hat probs with the older version

**Comment by Teifun2** [comment]
[penne_test.txt](https://github.com/mrzapp/nextcloud-cookbook/files/3949515/penne_test.txt)

Could you test this recipe for me?

**Comment by Teifun2** [comment]
I think it has to do with the fact that i missed to code the recipe standardization. ad7130fe45371d1a3fa38c789475fe619b0bab2e should do that now!

**Comment by xsus95** [comment]
Sorry for late reply. With 0.5.6 it works fine. Thanks
