### ISSUE TITLE
Is there an Android app?

### ISSUE THREAD

**Issue by GutHib** [mrzapp/nextcloud-cookbook#126]
Hi - very excited about this project, but now I realize there's no Android app to go with it, correct?

**Comment by Teifun2** [comment]
Correct. There is currently no Smartphone App for this Next cloud extension. There where some discussions about making one at some point, but as far as i understood this would need to wait until the nextcloud app itself is more fleshed out.

**Comment by mrzapp** [comment]
@danielroehrig was working on one some time ago, but not sure how it panned out. The API should be more or less working well enough to support an app, so AFAIK it's just the actual development we need.

@danielroehrig what have you got so far?

**Comment by danielroehrig** [comment]
Well, I created the project in my IDE a couple of months ago and that's it. I want to do it, but life and stuff gets in the way.

**Comment by mrzapp** [comment]
@danielroehrig No worries, it can't be more important than your personal life :) If you'd like help with it once you get time, let me know.
