### ISSUE TITLE
Hide image for the recipe printout

### ISSUE THREAD

**Issue by Help-i-am-lost** [mrzapp/nextcloud-cookbook#132]
Random feature request appears: If possible, please include an option to remove the image from the recipe printout. This would allow to print most recipes on a single A4 -sheet and thus save some paper and ink.

**Comment by mrzapp** [comment]
I'd actually cast a vote for hiding the image by default, as the use case for printing a photo seems like fringe to me.

If it's not important to make it optional, we can make the change in [this](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/css/style.css#L247) file

**Comment by Help-i-am-lost** [comment]
That was quick, got an update already and works as expected. Applause for mrzapp! :1st_place_medal:

**Comment by mrzapp** [comment]
It was so easy to just throw the change in there with the language patches, so I just went ahead :)
