### ISSUE TITLE
"Total time" and  "Total Time" 

### ISSUE THREAD

**Issue by cloud2018** [mrzapp/nextcloud-cookbook#133]
"Total Time" is not translated in German, when editing a recipe.

Two variants of "Total Time" are used:
recipe.php line42:<?php p($l->t('Total time'))
edit.php line 41: <?php p($l->t('Total Time'));

and only one is coded in /translationfiles/de/cookbook.po:
#: /srv/http/nc/apps/cookbook/templates/content/recipe.php:42
msgid "Total time"
msgstr "Gesamtzeit"

**Comment by christianlupus** [comment]
You are refferring to [this line in `recipe.php`](https://github.com/mrzapp/nextcloud-cookbook/blob/2593347eeb43d95fa135d7367bca2065d5489d4d/templates/content/recipe.php#L42) and [this line in `edit.php`](https://github.com/mrzapp/nextcloud-cookbook/blob/2593347eeb43d95fa135d7367bca2065d5489d4d/templates/content/edit.php#L41), right? For me both are written as `Total time`. Or are you referring another line/file?

There was a `Total Time` before I [merged them](https://github.com/mrzapp/nextcloud-cookbook/commit/1b23e98801d94c91abe3a7f39309eb6036606bec) together recently. Could it be the case, that you are not using the latest version from `develop` branch?

**Comment by cloud2018** [comment]
@christianlupus 
yes, your'e right, i check my installed version, not the code on github. sorry

**Comment by christianlupus** [comment]
No problem. You are welcome and thank for participating anyways.
