### ISSUE TITLE
PNG files are not shown

### ISSUE THREAD

**Issue by cubo42** [mrzapp/nextcloud-cookbook#134]
When trying to choose an image for a recipe, only JPEG files are shown and can be used (Image/"Pick a local image"), no PNG files can be chosen.

**Comment by mcorteel** [comment]
@mrzapp Sorry, I pushed my commit directly to your repository by accident. But it was a straitforward fix.

**Comment by mrzapp** [comment]
@mcorteel no worries, you committed it to the `v0.6.0` branch, which is experimental anyway. Honestly, it would have been fine for you to commit it to the `develop` branch, since it's just a patch.
