### ISSUE TITLE
Website Support: Betty Bossi

### ISSUE THREAD

**Issue by Mannshoch** [mrzapp/nextcloud-cookbook#139]
Please add Betty Bossi for receipe download.
Example rceipe:
https://www.bettybossi.ch/de/Rezept/ShowRezept/BB_AGXX970401_009a-40-de?title=Chapatis&list=c%3D%26f%3D10.104.207

**Comment by mrzapp** [comment]
This website doesn't implement schema.org properly. Or more accurately, I can see they're trying, but their HTML is malformed.

This recipe for instance: https://www.bettybossi.ch/de/Rezept/ShowRezept/BB_BBZB200215_0013A-40-de

Doesn't show up as a decorated result in search engines: https://duckduckgo.com/?t=ffab&q=Brot-Lauch-Gratin+bettybossi&ia=web

Closing, as there is nothing we can do about this. I recommend sending them a message about it.

**Comment by Mannshoch** [comment]
Thanks for evaluating.
:-(

**Comment by burrima** [comment]
Not sure if it is still relevant, but I found a possible work-around, which works for local, self-hosted Nextcloud installations (which are in the same network):

1. In Firefox (other browsers might work equally well), download/save the recipe page with ctrl-s
2. In the console (bash), navigate to the stored location, rename the complicated .html file to "index.html"
3. Use the command "python3 -m http.server" to start a local python-based web server in the same location where the index.html file is stored
4. Use the following import URL in Nextcloud: http://<ip-of-your-host>:8080/

Sounds a bit complicated, but is still much easier than re-typing the whole recipe :-)
