### ISSUE TITLE
Harden the database queries

### ISSUE THREAD

**Issue by christianlupus** [mrzapp/nextcloud-cookbook#14]
At the moment, the database entries seem not be quoted as far as I understand. So a normal user might use e.g. the search fields to do some SQL injection.

I saw this in when working on PR #12 for #5. Maybe I will find some time for a small PR but I wanted to keep this documented that there is a security vulerability.

**Comment by mrzapp** [comment]
@christianlupus You may be right about that. Luckily, only the [findRecipes](https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Db/RecipeDb.php#L85) method should be affected, so a small change to that should take care of it.

I'm no expert on SQL injection myself, so your contribution would be highly appreciated! :pray:

**Comment by christianlupus** [comment]
I just added the PR #25 for this issue.

**Comment by mrzapp** [comment]
@christianlupus great, thanks!
