### ISSUE TITLE
bbcgoodfood import fails while creating recipe image

### ISSUE THREAD

**Issue by Mic92** [mrzapp/nextcloud-cookbook#141]
Url: https://www.bbcgoodfood.com/recipes/spiced-carrot-lentil-soup

It shows a lot of warnings in the log like this:
```
Jan 27 10:00:30 eve Nextcloud[17920]: {"reqId":"tljNM2HRbeD6L7rc3SUv","level":3,"time":"2020-01-27T10:00:30+00:00","remoteAddr":"192.41.130.56","user":"joerg@h
iggsboson.tk","app":"PHP","method":"POST","url":"\/apps\/cookbook\/add","message":"DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 8 at \
/var\/lib\/nextcloud\/store-apps\/cookbook\/lib\/Service\/RecipeService.php#373","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:72.0) Gecko\/20100101 Firefox
\/72.0","version":"17.0.2.1"}
```

However those might be only warnings.
The website itself has the schema.org schema.

I get the following error message:

Could not add recipe: "\/joerg@higgsboson.tk\/files\/www.bbcgoodfood.com\/sites\/default\/files\/styles\/recipe\/public\/recipe_images\/recipe-image-legacy-id--1074500_11.jpg?itok=IwEifJO_"

![2020-01-27_11-41](https://user-images.githubusercontent.com/96200/73172047-0bab5180-40fa-11ea-87e4-60cf74a65ada.png)

I suppose the image name should be sanitized if not randomized. This might be even a security problem.

**Comment by mrzapp** [comment]
The image file URL `/joerg@higgsboson.tk/files/www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--1074500_11.jpg?` is pretty bonkers, BTW. It seems the linked recipe uses double forward slashes before the URL, maybe that's the issue

**Comment by Mic92** [comment]
Do you mean protocol less `//www.bbcgoodfood.com` instead of `http://www.bbcgoodfood.com`

**Comment by mrzapp** [comment]
Yea, exactly. I don't know yet whether that's the real problem with this site, though.

**Comment by mrzapp** [comment]
This will be pushed in 0.6.0

**Comment by Mic92** [comment]
It still does not load the image but at least creates the recipe anyway.
It is possible to fix the image url now manually by adding https:// in front.

**Comment by mrzapp** [comment]
@Mic92 can you check out the latest `master` and try again? I had overlooked this issue when testing

**Comment by Mic92** [comment]
Is all I need to to do cloning the cookbook to `/var/lib/nextcloud/store-apps/cookbook` and than run `npm`?

**Comment by mrzapp** [comment]
@Mic92 yes, but no need to run NPM
