### ISSUE TITLE
Editing recipe title creates a new recipe

### ISSUE THREAD

**Issue by mcorteel** [mrzapp/nextcloud-cookbook#142]
* Create a recipe called "Rice", save it
* Edit the recipe and rename it "White rice"
There are now two recipes : "Rice" and "White rice".

That doesn't seem like expected behavior, but maybe I'm mistaken. If not, I can create a pull request to fix that when I find the time.

**Comment by mrzapp** [comment]
That is a bug for sure. Are there 2 recipes in the search index or in the file system? Or both, perhaps?

**Comment by mrzapp** [comment]
Closing, as this will be fixed in 0.6.0

**Comment by dmbreakey** [comment]
This doesn't appear to be fixed; experiencing it in 0.6.2. At least I'm assuming this is a repeat of the same issue.

Some observations:

1. The extra entry appears to be a "phantom"; if I open either one, they both link to the same recipe, that has the correct title.
2. Checking the filesystem, the folder that the recipe is stored in was renamed to the new title, but the JSON file itself was not (it was still named using the original title). As a test, I tried renaming the JSON file to the expected (new) title, and it disappeared after a manual rescan. If I restore it back to the original filename, and rescan, it reappears, again with two entries.

For reference the one I attempted the rename with was the "Instant Pot Bacony Refried Beans" entry.

![Cookbook - Breakey Home - Google Chrome_565](https://user-images.githubusercontent.com/197063/77829685-44ab7680-70e9-11ea-936d-60e8ee302220.png)

**Comment by dmbreakey** [comment]
Some more observations:

Just updated to 0.6.3, and I've noticed that the duplicate entry issue only appears to happen when viewing the Category it is attached to; the "All Recipes" view shows just one entry, as expected.

How can I revert back to 0.6.2 to verify whether it happened with that release?

**Comment by Schlaubischlump** [comment]
@dmbreakey To my knowledge there is no easy way to downgrade a nextcloud app. You can download 0.6.2 from github and replace the changed files in the app folder manually. You can not copy the whole folder, because that will produce an NextCloud error each time you try to access the server.

**Comment by mrzapp** [comment]
@dmbreakey could you get the latest from `master`, rescan your library and try this again?

**Comment by dmbreakey** [comment]
Sure; I'll try to remember to do it tonight. Assuming I can just to a Git checkout, then copy the files over into apps/cookbook?

**Comment by mrzapp** [comment]
@dmbreakey yep, that's pretty much it

**Comment by dmbreakey** [comment]
np; I'll try to remember to check tonight then.

**Comment by dmbreakey** [comment]
That appears to fix it. The category now shows one entry, as expected. Additionally, I tested renaming another one, and it appears to work as expected.
