### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by mrzapp** [mrzapp/nextcloud-cookbook#143]
UI changes for v0.6.0 as per @mcorteel's initiative:

- Use global search
- Add home page
- Add control bar
- Use navigation bar as category selector
- Show recipes in main area
- Remove keyword selector

**Comment by mcorteel** [comment]
I actually included a lot of interface changes in pull request #144:

* A revamped recipe page
* A new menu based on tags (to be based on `recipeCategory` in the future)
![Capture d’écran - 2020-02-02 à 14 47 21](https://user-images.githubusercontent.com/6164603/73609128-eff8ed00-45ca-11ea-9874-bdda75f02a21.png)

* A new recipe list
![Capture d’écran - 2020-02-02 à 14 49 12](https://user-images.githubusercontent.com/6164603/73609157-39493c80-45cb-11ea-9b2f-1e96a16ab1ff.png)

**Comment by mrzapp** [comment]
@mcorteel dang, that looks sweet! I'll test this ASAP.

**Comment by mrzapp** [comment]
Closing, as all goals mentioned here have been addressed in #144
