### ISSUE TITLE
Thumbnail images are inverted colours when using dark theme

### ISSUE THREAD

**Issue by budokaiman** [mrzapp/nextcloud-cookbook#146]
When using dark theme, thumbnail images in the recipe list appear with inverted colours (ie. they look like negatives).

**Comment by mcorteel** [comment]
@budokaiman I don't see this problem. Can you join a screenshot?
And what is your accessibility configuration exactly? Also, what is your nextcloud version?

**Comment by budokaiman** [comment]
I'm on the latest version of 18.0.0, my accessibility configuration is just having dark theme enabled, high contrast and dyslexia font are both disabled. Below is the screenshots of dark theme enabled then disabled. You can see how the bread becomes blue with dark theme enabled.

<img width="225" alt="2020-02-04 06_49_51-Cookbook - Nextcloud" src="https://user-images.githubusercontent.com/2196125/73742742-162da280-471b-11ea-9152-3ef2e075b2b6.png">

<img width="225" alt="2020-02-04 06_50_27-Cookbook - Nextcloud" src="https://user-images.githubusercontent.com/2196125/73742731-0f9f2b00-471b-11ea-8637-203739299fcb.png">

**Comment by theonlytruth** [comment]
Same problem here. Also with NC18 and dark theme.

**Comment by mcorteel** [comment]
Right, I wasn't looking in the right place...
This is Nextcloud accessibility behavior, it's not specific to this app. So this should be debated upstream.
Anyway, if #144 is merged, this design will disappear (see my screenshots in #143).

**Comment by mrzapp** [comment]
Closing as this is not Cookbook specific
