### ISSUE TITLE
F-Droid App "Drinks"

### ISSUE THREAD

**Issue by Mannshoch** [mrzapp/nextcloud-cookbook#148]
https://f-droid.org/en/packages/fr.masciulli.drinks/
https://github.com/amasciul/Drinks

If I understood it right this App gets It's recipes from Wikipedia.
I see two possibility 

1. add wkipedia as source for recipes.
1. work together with this app for an Android recipe app.

**Comment by mrzapp** [comment]
That app is not really related to us. The NextCloud Cookbook app only presents recipes that you store on your own NextCloud instance, not the public internet. There are plenty other recipe apps that do that.

**Comment by Mannshoch** [comment]
The idea was to take this code for your own app or work together with them to get nextcloud as a source into this app.

I did not meant you are somehow releated to the dev of this app.
