### ISSUE TITLE
Feature wanted: multiple ingredient lists

### ISSUE THREAD

**Issue by MikeOlsen** [mrzapp/nextcloud-cookbook#15]
The ability to have multiple ingredient lists and maybe instructions for more advanced recipes. 
In example a recipe for a pie, where the dough has one ingredient list, the filling one and the sauce a third.

**Comment by poltrian** [comment]
I make These

First Line ingedients:
Doug:
Flour 200g
Milk 109ml
Butter 100g

For Sauce also one Line
Sauce:
Tomato
Salt
Oil

Topping:
Cheese
....
...






MikeOlsen <notifications@github.com> schrieb am Fr., 12. Juli 2019, 19:51:

**Comment by mrzapp** [comment]
@MikeOlsen Alas, it seems this is not supported by the [schema.org](https://schema.org/Recipe) standard.
