### ISSUE TITLE
Feature request: Reorganise list fields

### ISSUE THREAD

**Issue by alexlienert** [mrzapp/nextcloud-cookbook#151]
Hello,
thanks for the work! This is a super addon ;).

Things that I recommend and that are already recommended:
- direct PDF export ( that in the recipe folder is the ready to use/share pdf. Maybe a easy autocreate PDF after saving the recipe would do the trick )
- share a PDF or the addon site as a viewer (for people without nc)
----------------------------- 
- APP

I know sharing is possible with printing to PDF and storing the document on the cloud than sharing the file via link etc. but..

I like the organization of fields but when you are working on a recipe you sometimes need to change the workflow. Actually when you want to insert a step between you only can add it to the end and move all entries by copy+paste through all the fields. I'm not into web development but maybe there are some easy ways to add a movement for the ingredients and workflow fields.

Greetings Alex

**Comment by mrzapp** [comment]
I see your point, that would actually be really nice UX

**Comment by mrzapp** [comment]
This is now ready for testing in the 0.6.0 branch
