### ISSUE TITLE
Integrate Links to working Recipes Site

### ISSUE THREAD

**Issue by duesseldorferjung** [mrzapp/nextcloud-cookbook#155]
Big thank you for this great add-on!
As I am moving my "life" to the cloud including removing all my paper cookbooks, it helps a lot.
For people who are just starting to use it I feel it would be a great help to have a link within the add-on pointing to working recipes sites. In addition to that everybody could commit additional sites in github and everybody could benefit.

**Comment by mrzapp** [comment]
Well, if the site has implemented schema.org correctly, it should work without problems. It would be much easier making a list of sites that **don't** work, since most sites do.
