### ISSUE TITLE
iOS / macOS Client

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#158]
Hi Jeppe, 

Actually this is not an issue. I just didn't know how to reach you. First off: I really love your project ! Great work !

Now back to the topic:
I wrote an iOS / macOS client for Cookbook, which is still in early development. At the moment only viewing recipes is possible, so adding / editing / deleting is not yet possible. You can check it out at: [Cookbook-Client](https://github.com/Schlaubischlump/Cookbook-Client). 

Keep up the good work!

**Comment by mrzapp** [comment]
Hey, nice work! You might want to talk to @danielroehrig who started work on an Android app a while back and made some changes to the API
