### ISSUE TITLE
Feature wanted: Left side structured by treeview

### ISSUE THREAD

**Issue by jgrete** [mrzapp/nextcloud-cookbook#16]
Hi,
I would like to see a treeview on the left side and may be a separated favorites section (which
includes a favorite marker for everey receipe)
Thanks alot for your good work
Jürgen

**Comment by horga83** [comment]
I was thinking about this and maybe the easiest way is to have a tree view of folders one can select.  For example:

recipes/salads
recipes/pasta
recipes/desserts

and so on, then just choose the folder out of a list or better yet a treeview
Thoughts?

**Comment by mrzapp** [comment]
What would be doable at the present moment would be to group recipes by tags. I'm trying to stay compatible with the schema.org standard. Would that suffice?

**Comment by GideonWolfe** [comment]
Any updates on this? I would love some way to categorize recipes.

**Comment by mrzapp** [comment]
@GideonWolfe I'm looking for someone to start this contribution, as I don't have a lot of time to work on this myself. Currently, I think the best would be to optionally categorise them by tags.

We would have to add folder nesting to [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/templates/navigation/recipes.php) view

The option to enable/disable the categorisation could be a checkbox in [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/templates/navigation/index.php) view

Would you like to give that a try?

**Comment by jgrete** [comment]
Hello,
I think structuring things  like receipes is not an easy task and in my opinion the best method
 would be to combine tags and treeview. 
This could be done with a global filter containing tags and filtering all those receipes not containing one of the tags. I remember eclipse has something similar in it's settings dialog (treeview + tag). The tag entry field  could be set by the user dynamically to reduce the set of receipes to a subset.
The overall look and feel would be determined by the treeview. 
Just some thoughts...
My php knowledge is near zero so I can not contribute - sorry. I would happily testing though...
Regards
Jürgen

**Comment by christianlupus** [comment]
I have another idea/suggestion. I am not sure if this might help, work out and be compatible to the standard...

Are the tags allow special chars like a `-` or `/`? In this case, one could combine both approaches by using semantic tags. One could have tags like `italien/pizza`, and `italian/pasta` which describe a hirachrical structure of tags. In the navigation area one could then build a graphical representation of this tree for filtering/sorting.

Of course there are quite some UI problems to be solved. I first wanted to ask if this looks as a feasible way.

**Comment by mrzapp** [comment]
@christianlupus Tags are just strings, however we present the frontend is not necessarily schema dependent. I think it sounds like a good idea.

**Comment by mrzapp** [comment]
I've made a keyword dropdown for now, we can reopen this issue later if needed
