### ISSUE TITLE
Print Recipe with Image

### ISSUE THREAD

**Issue by phantomdez** [mrzapp/nextcloud-cookbook#161]
I cannot seem to find an option for this and maybe it hasn't been added as of yet but when I try to print the recipie it doesn't add an image.  Am I missing an option or has this been done by design?  My wife would like to include a image for her physical copies that she keeps in here Recipe binder.

Thanks

**Comment by mcorteel** [comment]
Yes, it is by design. I guess an option would make sense. @mrzapp?

**Comment by mrzapp** [comment]
@mcorteel if so, should we make the print button a dropdown menu with 2 options, with and without pictures?

**Comment by mcorteel** [comment]
It's a possibility, but I think that it goes against Nextcloud UI guidelines. I would have implemented it as a global option, but I guess it's not great either.
Maybe we should ask the Nextcloud usability guys? I'm not sure, but I guess @jancborchardt would be the way to go. Any comment?

**Comment by jancborchardt** [comment]
I’m glad to help, but could I get some more context, maybe in the form of screenshots? :)

@mcorteel you mention it is leaving out images by design, why is that? If the recipe has an image set, I would expect it to be printed as well. Especially for recipes, an image makes it much nicer.

**Comment by mrzapp** [comment]
@jancborchardt it was just what we considered common sense at the time, saving ink and all that. But it wasn't intended to be restrictive, we should definitely add it as an option, if it's wanted.

**Comment by phantomdez** [comment]
I would definitely vote to have it as an option.  I brought this up as I thought I was missing a setting but since I see it isn't [Thank you all for your responses] I would vote to add it as an option.

**Comment by cloud2018** [comment]
In Cookbook 0.7.6 the text in Settings is "Print image with recipe". I think "Print recipe with image" is more popular. 
![cb20202627](https://user-images.githubusercontent.com/34692335/85921274-71536380-b87b-11ea-82ab-3a7e500dccec.png)

**Comment by mrzapp** [comment]
@cloud2018 patches welcome here too :)
