### ISSUE TITLE
Could not add recipe: "No default encryption module defined" (while encryption enabled)

### ISSUE THREAD

**Issue by beatstick** [mrzapp/nextcloud-cookbook#162]
I get the above error when trying to add a recipe via web address. Systemwide encryption is enabled on Nextcloud 18.01.

**Comment by mrzapp** [comment]
@beatstick could you possibly narrow down a little further where the error happens? It should be visible in the log, if I'm not wrong

**Comment by mrzapp** [comment]
No problem, thanks for updating us :)

**Comment by sneak** [comment]
Could you please tell the rest of us who are having this issue (having enabled systemwide encryption with the checkbox, who are now receiving this error) how to install the dependencies for systemwide encryption?

I don't see a "default encryption module" in the app list.
