### ISSUE TITLE
List of recipes as json

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#163]
Hi Jeppe, 

I have a little problem with the new routes introduced in v.0.6. I can't find a way to download a list of recipes as json format (is there any way?), because none of the calls in RecipeController have been exposed in the routes.php file. It would be nice to have direct way to access the json data, because otherwise it's near to impossible to write a thrid party client application.

**Comment by mrzapp** [comment]
@mcorteel did the API endpoints perhaps change with your router rewrite?

**Comment by Schlaubischlump** [comment]
Nevermind, I just didn't see the endpoint... All recipe requests where moved to `'recipe' => ['url' => '/api/recipes']`. I close the issue.

**Comment by mrzapp** [comment]
@Schlaubischlump ah, right, this was by @mcorteel's more consistent design. I don't think the image resource should be an API endpoint, since it's not a JSON response, it's intended to be for rendering only.

**Comment by Schlaubischlump** [comment]
Alright, Thanks for your quick help !

**Comment by mcorteel** [comment]
I confirm. Sorry for the late answer!
And yes @mrzapp I guess the image shouldn't be part of the `/api` endpoints.
