### ISSUE TITLE
"No category" label displays the wrong number of recipes

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#167]
Steps to reproduce: 
1. Delete a recipe
2. The sidebar information is not update

![Screenshot](https://user-images.githubusercontent.com/15728815/77406930-aa2ff800-6db5-11ea-8ef9-dd437577b90b.png)

As you can see in the screenshot, I only have one recipe left in my library and the label still shows 79 recipes. Restarting the nextcloud server and rescanning the library does not fix this error.

**Comment by mrzapp** [comment]
Forgot to include the "recipe_categories" table in the database functions, should be fixed in `master` now

**Comment by Schlaubischlump** [comment]
Perfect, Thank you !
