### ISSUE TITLE
Reload the recipe list after rescanning the library

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#168]
Not a big issue, just a minor inconvenience. If this "bug" is not deemed worth to be fixed, just close this issue.

Steps to reproduce: 

1. Manually upload / delete a recipe from the folder structure (not in the cookbook app)
2. Open the cookbook app and rescan the library
3. The "All recipes" list does not update. You have to manually click on the "All recipes" sidebar entry to reload the view.

**Comment by mrzapp** [comment]
A minor usability fix, but worth it
