### ISSUE TITLE
Exported pdf contains empty space

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#169]
If you open a recipe which has an image attached to it and click on the print dialog the exported pdf file will include an empty space at the top of the document. Tested on macOS 10.15.3 with Safari 13.0.5 and Firefox 74.0.

Steps to reproduce:
1. Open a recipe with an image
2. Click print
3. Export to pdf

Example :
Note: Although it looks like the content is centered, this is not the case. If you add more Metadata to the recipe the space at the top stays the same.

![bug](https://user-images.githubusercontent.com/15728815/77410776-b919a900-6dbb-11ea-9dc2-f4e4d7fb9910.png)

**Comment by mrzapp** [comment]
@mcorteel you think you can look into adapting your new layout to print? There is a query at the bottom of the CSS file.

**Comment by Schlaubischlump** [comment]
I will look into it, but I'm not that good at css. I will probably take a little bit of time

**Comment by mcorteel** [comment]
I'm on it. Also, the timer button should not appear when printing!

**Comment by mcorteel** [comment]
I guess that should solve the problem.
Note: this will change if we implement #161.

**Comment by mrzapp** [comment]
Released in 0.6.2
