### ISSUE TITLE
Feature wanted: Export to pdf

### ISSUE THREAD

**Issue by jgrete** [mrzapp/nextcloud-cookbook#17]
Hi, another wish - I know, I'm going to be impertinent...
I would like to make an export to pdf of a receipe and store that on my cloud
Thanks again for your work, the next wishes not before december :-)
Jürgen

**Comment by sir-indy** [comment]
Would you be happy with printing the page rather than an export button? You could print to PDF and save that.
I noticed that the Notes app prints out nicely, I'm no CSS expert but I did find this in the Notes app:

`@media print {
    #header,
    #app-navigation,
    #note-container .action-buttons {
        display: none !important
    }
    #content {
        display: block;
        padding: 0
    }
    #note-container .note-editor,
    #note-container .note-preview {
        padding: 0 !important;
        font-size: 10pt !important
    }
    #app-content {
        margin-left: 0 !important
    }
}`

It hides the header, app-navigation and note-container from the print view. Could we do something similar with the cookbook?

**Comment by sir-indy** [comment]
Just had a brief fiddle and this needs popping in the CSS somewhere:
`@media print { 
    #header, 
    #app-navigation, 
    #note-container .action-buttons { 
        display: none !important 
    } 
    #content { 
        display: block; padding: 0 
    } 
    #app-content { 
        margin-left: 0 !important }
    a:link:after, a:visited:after { content:" [" attr(href) "] "; }
}`

Code nicked from: 
https://github.com/nextcloud/notes/blob/master/css/print.scss
https://davidwalsh.name/optimize-your-links-for-print-using-css-show-url

**Comment by mrzapp** [comment]
@sir-indy if you feel this works for you, I'll be happy to merge it

**Comment by okcomputerik** [comment]
This would be great to also share the recipes! Although I don't know how hard it would be to add a "Share recipe" option to each recipe, like with files, so that people could access only that recipe, for instance.
Thanks for the great work!

**Comment by jgrete** [comment]
Printing would be sufficient of course.
@okcomputerik 's proposal would also be a very nice feature to have!

**Comment by mrzapp** [comment]
A print button has been added in the next release, you can use that to print to PDF if needed :)
