### ISSUE TITLE
possible vandalism

### ISSUE THREAD

**Issue by HieronymusCH** [mrzapp/nextcloud-cookbook#18]
Maybe I'm just a little too paranoid here, but my test user was allowed to delete recipes it did not create.

Should cookbook work this way?

**Comment by mrzapp** [comment]
@HieronymusCH Recipes are stored wherever you specify in the settings, so unless you pointed the app to a shared directory, the current user shouldn't even be able to even see recipes they didn't create.

In short, the user can delete any recipe they can see. This is based on NextCloud's permissions. Creating a new permissions system for this app is out of scope, I'm afraid :sweat_smile:
