### ISSUE TITLE
[Bug] Error at saving recipes (after update)

### ISSUE THREAD

**Issue by funky123** [mrzapp/nextcloud-cookbook#184]
after updating to version 0.6.3 there is an error everytime i save a recipe there is a error message.
it seems to save the content, after i manually refresh the browsers cache or start a rescan of the libary the changes are visible.

besides that, i now need to take all my tags for each receipt and use the new categoty feature. isn'nt there a batch way of doing that? 

i attach the errors from my nextcloud log and a screenshot from the error message itself.

![Screen-1 before Saving  2020-04-02 181940](https://user-images.githubusercontent.com/12056510/78279489-e0891800-7517-11ea-99db-3a8b638666a4.jpg)
![Screen-2 after saving  2020-04-02 181940](https://user-images.githubusercontent.com/12056510/78279491-e1ba4500-7517-11ea-8a6e-beee6273b4ee.jpg)
![Screen-3 Logs NC  2020-04-02 181940](https://user-images.githubusercontent.com/12056510/78279687-36f65680-7518-11ea-8774-b6d548f8c68a.jpg)

Here are the log files first entry from screenshot 3

`{"reqId":"LTG8JeDzYyfpeRXsF50X","level":3,"time":"2020-04-02T19:20:23+02:00","remoteAddr":"77.179.106.93","user":"m.welter","app":"index","method":"PUT","url":"/apps/cookbook/recipes/10755/edit","message":{"Exception":"Exception","Message":"Call to undefined method OCP\\Files\\Cache\\CacheUpdateEvent::setPath()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"update"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","update",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"10755","_route":"cookbook.main.update"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"10755","_route":"cookbook.main.update"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"10755","_route":"cookbook.main.update"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/cookbook/recipes/10755/edit"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined method OCP\\Files\\Cache\\CacheUpdateEvent::setPath()","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"onCacheEvent","class":"OCA\\GroupFolders\\CacheListener","type":"->","args":[{"__class__":"OCP\\Files\\Cache\\CacheUpdateEvent"},"OCP\\Files\\Cache\\CacheUpdateEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\Files\\Cache\\CacheUpdateEvent",{"__class__":"OCP\\Files\\Cache\\CacheUpdateEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Files\\Cache\\CacheUpdateEvent"},"OCP\\Files\\Cache\\CacheUpdateEvent"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":63,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Files\\Cache\\CacheUpdateEvent",{"__class__":"OCP\\Files\\Cache\\CacheUpdateEvent"}]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php","line":393,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["OCP\\Files\\Cache\\CacheUpdateEvent",{"__class__":"OCP\\Files\\Cache\\CacheUpdateEvent"}]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":140,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php","line":133,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":140,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheJail","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/RootEntryCache.php","line":52,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":140,"function":"update","class":"OCA\\GroupFolders\\Mount\\RootEntryCache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php","line":140,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":290,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":222,"function":"addToCache","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":337,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",3,10755,{"__class__":"OC\\Files\\Cache\\CacheEntry"},false]},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Updater.php","line":124,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",false,3,false]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":321,"function":"update","class":"OC\\Files\\Cache\\Updater","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1177,"function":"writeUpdate","class":"OC\\Files\\View","type":"->","args":[{"mountPoint":"/m.welter/files/Rezepte/","cache":{"__class__":"OC\\Files\\Cache\\Cache"},"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":{"__class__":"OC\\Files\\Cache\\Updater"},"__class__":"OCA\\FilesAccessControl\\StorageWrapper"},"*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":694,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_put_contents","/m.welter/files/Rezepte/Baguette/Baguette.json",["update","write"],"{\"name\":\"Baguette\",\"description\":\"\",\"url\":\"\",\"image\":\"\",\"prepTime\":\"PT0H0M\",\"cookTime\":\"PT0H0M\",\"totalTime\":\"PT0H0M\",\"recipeCategory\":\"Brot\\/Br\\u00f6tchen\",\"keywords\":\"Brot\\/Br\\u00f6tchen\",\"recipeYield\":2,\"recipeIngredient\":[\"10 g Hefe\",\"300 ml Wasser\",\"1 Prise Zucker\",\"380g Dinkelmehl\",\"1 TL Salz\"],\"recipeInstructions\":[\"Die Hefe mit dem Zucker im Wasser aufl\\u00f6sen. Mehl und Salz hinzuf\\u00fcgen und alles kurz umr\\u00fchren, bis alles vollst\\u00e4ndig verbunden ist. Den Teig abdecken und f\\u00fcr 2 Stunden bei Zimmertemperatur aufgehen lassen.\",\"Reichlich Mehl auf der Arbeitsfl\\u00e4che verteilen und den Teig vorsichtig drauf sch\\u00fctten, ohne zu viel Luft rauszudr\\u00fccken. Den Teig mit Mehl bestreuen und in drei gleichgro\\u00dfe Portionen teilen.\",\"Die Teige nun auf ein Blech legen und im vorgeheizten Backofen bei 240\\u00b0C Hei\\u00dfluft f\\u00fcr etwa 20 Minuten backen. Hierbei einen feuerfesten Beh\\u00e4lter\\/Auflaufform mit reichlich Wasser zus\\u00e4tzlich in den Backofen stellen.\"],\"id\":\"10755\",\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"Recipe\",\"tool\":[]}"]},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":71,"function":"file_put_contents","class":"OC\\Files\\View","type":"->","args":["/m.welter/files/Rezepte/Baguette/Baguette.json","{\"name\":\"Baguette\",\"description\":\"\",\"url\":\"\",\"image\":\"\",\"prepTime\":\"PT0H0M\",\"cookTime\":\"PT0H0M\",\"totalTime\":\"PT0H0M\",\"recipeCategory\":\"Brot\\/Br\\u00f6tchen\",\"keywords\":\"Brot\\/Br\\u00f6tchen\",\"recipeYield\":2,\"recipeIngredient\":[\"10 g Hefe\",\"300 ml Wasser\",\"1 Prise Zucker\",\"380g Dinkelmehl\",\"1 TL Salz\"],\"recipeInstructions\":[\"Die Hefe mit dem Zucker im Wasser aufl\\u00f6sen. Mehl und Salz hinzuf\\u00fcgen und alles kurz umr\\u00fchren, bis alles vollst\\u00e4ndig verbunden ist. Den Teig abdecken und f\\u00fcr 2 Stunden bei Zimmertemperatur aufgehen lassen.\",\"Reichlich Mehl auf der Arbeitsfl\\u00e4che verteilen und den Teig vorsichtig drauf sch\\u00fctten, ohne zu viel Luft rauszudr\\u00fccken. Den Teig mit Mehl bestreuen und in drei gleichgro\\u00dfe Portionen teilen.\",\"Die Teige nun auf ein Blech legen und im vorgeheizten Backofen bei 240\\u00b0C Hei\\u00dfluft f\\u00fcr etwa 20 Minuten backen. Hierbei einen feuerfesten Beh\\u00e4lter\\/Auflaufform mit reichlich Wasser zus\\u00e4tzlich in den Backofen stellen.\"],\"id\":\"10755\",\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"Recipe\",\"tool\":[]}"]},{"file":"/var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php","line":562,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->","args":["{\"name\":\"Baguette\",\"description\":\"\",\"url\":\"\",\"image\":\"\",\"prepTime\":\"PT0H0M\",\"cookTime\":\"PT0H0M\",\"totalTime\":\"PT0H0M\",\"recipeCategory\":\"Brot\\/Br\\u00f6tchen\",\"keywords\":\"Brot\\/Br\\u00f6tchen\",\"recipeYield\":2,\"recipeIngredient\":[\"10 g Hefe\",\"300 ml Wasser\",\"1 Prise Zucker\",\"380g Dinkelmehl\",\"1 TL Salz\"],\"recipeInstructions\":[\"Die Hefe mit dem Zucker im Wasser aufl\\u00f6sen. Mehl und Salz hinzuf\\u00fcgen und alles kurz umr\\u00fchren, bis alles vollst\\u00e4ndig verbunden ist. Den Teig abdecken und f\\u00fcr 2 Stunden bei Zimmertemperatur aufgehen lassen.\",\"Reichlich Mehl auf der Arbeitsfl\\u00e4che verteilen und den Teig vorsichtig drauf sch\\u00fctten, ohne zu viel Luft rauszudr\\u00fccken. Den Teig mit Mehl bestreuen und in drei gleichgro\\u00dfe Portionen teilen.\",\"Die Teige nun auf ein Blech legen und im vorgeheizten Backofen bei 240\\u00b0C Hei\\u00dfluft f\\u00fcr etwa 20 Minuten backen. Hierbei einen feuerfesten Beh\\u00e4lter\\/Auflaufform mit reichlich Wasser zus\\u00e4tzlich in den Backofen stellen.\"],\"id\":\"10755\",\"@context\":\"http:\\/\\/schema.org\",\"@type\":\"Recipe\",\"tool\":[]}"]},{"file":"/var/www/nextcloud/apps/cookbook/lib/Controller/MainController.php","line":259,"function":"addRecipe","class":"OCA\\Cookbook\\Service\\RecipeService","type":"->","args":[{"name":"Baguette","description":"","url":"","image":"","prepTime":"PT0H0M","cookTime":"PT0H0M","totalTime":"PT0H0M","recipeCategory":"Brot/Brötchen","keywords":"Brot/Brötchen","recipeYield":2,"recipeIngredient":["10 g Hefe","300 ml Wasser","1 Prise Zucker","380g Dinkelmehl","1 TL Salz"],"recipeInstructions":["Die Hefe mit dem Zucker im Wasser auflösen. Mehl und Salz hinzufügen und alles kurz umrühren, bis alles vollständig verbunden ist. Den Teig abdecken und für 2 Stunden bei Zimmertemperatur aufgehen lassen.","Reichlich Mehl auf der Arbeitsfläche verteilen und den Teig vorsichtig drauf schütten, ohne zu viel Luft rauszudrücken. Den Teig mit Mehl bestreuen und in drei gleichgroße Portionen teilen.","Die Teige nun auf ein Blech legen und im vorgeheizten Backofen bei 240°C Heißluft für etwa 20 Minuten backen. Hierbei einen feuerfesten Behälter/Auflaufform mit reichlich Wasser zusätzlich in den Backofen stellen."],"id":"*** sensitive parameter replaced ***","@context":"http://schema.org","@type":"Recipe","tool":[]}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"update","class":"OCA\\Cookbook\\Controller\\MainController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"update"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"update"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","update",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"*** sensitive parameter replaced ***","_route":"cookbook.main.update"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"*** sensitive parameter replaced ***","_route":"cookbook.main.update"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"*** sensitive parameter replaced ***","_route":"cookbook.main.update"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/cookbook/recipes/10755/edit"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/groupfolders/lib/CacheListener.php","Line":49},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","version":"18.0.1.3","id":"5e8620813d6d6"}`

2. entry

`{"reqId":"gw8F1pi2sqC8BC4qSnBW","level":3,"time":"2020-04-02T19:20:01+02:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"\"continue\" targeting switch is equivalent to \"break\". Did you mean to use \"continue 2\"? at /var/www/nextcloud/apps/workflowengine/lib/Helper/LogContext.php#55","userAgent":"--","version":"18.0.1.3","id":"5e8620813d6ee"}`

do you need mor info or logs? let me know.

Running on a local NC ubunut 18.04

**Comment by mrzapp** [comment]
Hm, the error that appeared `Call to undefined method OCP\\Files\\Cache\\CacheUpdateEvent::setPath()` seems unrelated to this app, as we don't interact directly with the file cache at any point.

Is the rest of your NextCloud instance up to date?

**Comment by funky123** [comment]
updating NC to 18.03 solved the issue. thanks for your good work, your time and perfect hint ;)

**Comment by mrzapp** [comment]
No problem :)
