### ISSUE TITLE
[Feature Request] Allow translation of default folder

### ISSUE THREAD

**Issue by drikqlis** [mrzapp/nextcloud-cookbook#186]
Currently when user is entering the app for the first time the "Recipes" folder is created no matter what language of Nextcloud is set. It would be great if this name/location could be translated or set by administrator.

**Comment by mrzapp** [comment]
Agreed, and it would be a simple fix

**Comment by christianlupus** [comment]
I am not so sure about this.

Depending what happens first (user setting language default and app folder is generated) there is no chance the change the language before the folder structure is set up (you might know better when the folder is generated after a vanilla installation).
Additionally: What should happen when the user changes the localization? Rename the folder? Keep it persistent?

Just my 50ct

**Comment by drikqlis** [comment]
I would say that in most cases Nextcloud instances are one-language and default language is set by administrator. Additionally according to my tests on my instance, folder generation happens once user enters the app for the first time, or if he deletes the folder - after creating the first recipe. 

Also it shouldn't be changed after that automatically to avoid confusion. Maybe it has some disadvantages, but it would still be better than current approach to generate English-named folder for users who don't know English.

**Comment by mrzapp** [comment]
I agree with @drikqlis, but @christianlupus' concern brings up a good point. We should make sure to store the fallback path with the localised recipe folder name in the user settings the first time they open the app. That way, the path will remain unchanged when user changes the language.
