### ISSUE TITLE
Can't Open Between Users?

### ISSUE THREAD

**Issue by MolsonFL** [mrzapp/nextcloud-cookbook#19]
I have added recipes using URLs under my admin account as well as a created user account.  Both accounts can see all of the recipes but cannot open them from the opposite account.  When attempting to edit, dialog is thrown stating recipe could not be opened.

Please let me know what information you might need on my end and I will do my best to provide it.

**Comment by mrzapp** [comment]
If you want to share recipes between users, you need specify a shared folder in the settings for the app to store the json files.
