### ISSUE TITLE
Dark theme makes printing unusable

### ISSUE THREAD

**Issue by geeseven** [mrzapp/nextcloud-cookbook#192]
When using the included dark theme or [nextcloud-breeze-dark][0], PDFs get created with a dark theme.  This is undesirable for printing.  Maybe an option to ignore theme should get added. 

[0]: https://github.com/mwalbeck/nextcloud-breeze-dark

**Comment by mcorteel** [comment]
Dark theme should not be applied when printing. But isn't this a Nextcloud issue?

**Comment by mrzapp** [comment]
@mcorteel maybe, but we could still override it with some fabulous `!important` statements, if needed ;)

**Comment by mcorteel** [comment]
I created an issue upstream. It would be a horrible hack to fix it in the cookbook app (unless I'm missing something, we would have to reset color variables, which seems wrong).

**Comment by mrzapp** [comment]
@mcorteel absolutely agreed, I'll close this issue then
