### ISSUE TITLE
The timers (prep, cooking and total times) shouldn't impose a specific limit, unless required by technical limitations.

### ISSUE THREAD

**Issue by dmbreakey** [mrzapp/nextcloud-cookbook#193]
Some recipes (eg: https://www.foodnetwork.com/recipes/alton-brown/wild-sourdough-starter-7480403) require unusually long times.

**Comment by mrzapp** [comment]
@dmbreakey where are you seeing a time limit?

**Comment by dmbreakey** [comment]
When entering values for the various recipe timers, if I try to enter more than 99 hours, it marks the field as red, and then when I try to save it, I get a tooltip: "Value must be less than or equal to 99".
