### ISSUE TITLE
images with href without scheme don't work

### ISSUE THREAD

**Issue by crazystick** [mrzapp/nextcloud-cookbook#195]
This happens on all the recipes on BBC Good Food for example.

This url: https://www.bbcgoodfood.com/recipes/roast-lamb-studded-rosemary-garlic

produces an alert in the browser with the message:

```
Could not add recipe: "\/userl\/files\/www.bbcgoodfood.com\/sites\/default\/files\/styles\/recipe\/public\/user-collections\/my-colelction-image\/2015\/12\/recipe-image-legacy-id--219622_12.jpg?itok=NAuIZbCY"
```

Recipe is actually added, but the image doesn't load until you manually add "https" in front of it.

**Comment by mrzapp** [comment]
Dangit, I thought we'd killed that bug.

The check for these kinds of URLs is here, but we might have overlooked something: https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L171
