### ISSUE TITLE
hidden text should be ignored when downloading recipes

### ISSUE THREAD

**Issue by crazystick** [mrzapp/nextcloud-cookbook#196]
On BBC Good Food, there are divs that show some text when you hover over some ingredients.

Example URL: https://www.bbcgoodfood.com/recipes/roast-lamb-studded-rosemary-garlic

This text that is hidden should not be included in the text of the ingredients list. For this specific site, there are two possible solutions:

1. There's a `content` attribute on the `li` for the ingredient, that contains the correct text
2. The unwanted text in the hover is contained in a div with `aria-hidden="true"` and so could be ignored as screenreaders should.

**Comment by mrzapp** [comment]
As a quick fix, we could prioritise the "content" attribute over the inner content.
