### ISSUE TITLE
Pressing enter while in ingredients list should perform add

### ISSUE THREAD

**Issue by vozeldr** [mrzapp/nextcloud-cookbook#20]
While manually entering ingredients in the list, pressing enter should add a new row and set the focus to the new row. Currently, pressing enter in the ingredients list causes the value entered in the current row to be lost.

**Comment by mrzapp** [comment]
@vozeldr I suppose that's because "enter" means "submit form". I'll happily welcome a pull request, if you've got an implementation in mind.

**Comment by horga83** [comment]
I think this is an important feature.  It's very confusing for new users.  Took me a 3 or 4 tries before I clued in and my daughter and wife didn't get it until I told them.  They just thought the app was broken.

Hope you will consider this a bug and not a feature request.

**Comment by mrzapp** [comment]
@horga83 I'll consider it a bug, sure

**Comment by mrzapp** [comment]
Should be fixed now, I'll publish a new patch

**Comment by horga83** [comment]
Many thanks, it's much appreciated, I forked the repo and started looking at the source but you know that takes awhile to get familiar with it.
