### ISSUE TITLE
Feature request: Import from PDF

### ISSUE THREAD

**Issue by AlexanderSch90** [mrzapp/nextcloud-cookbook#200]
It would be nice if you could read a PDF instead of a URL. If this doesn't work, it would be nice if you could deposit a PDF. Only in this way is it possible for me to import my previous recipe book without extreme effort.

**Comment by mrzapp** [comment]
The trouble is that PDFs don't really store meta data about all the text in them, it's just pure text (and often not even that, just vector paths), so we'd have to train an AI to interpret the PDF into JSON format.

That would actually be a super neat project, but definitely out of scope for this humble NextCloud app :smile:
