### ISSUE TITLE
Use itemprop content attribute as fallback for all fields parsed via HTML

### ISSUE THREAD

**Issue by heliohenriques** [mrzapp/nextcloud-cookbook#201]
Good afternoon,
Before start, congratulations for the idea and the app developed. 

I'm installed the nextcloud-cookbook few weeks ago, and it's really interesting the way of import receipts with a URL.

The question / suggestion is if possible:
When isn't possible to import direct from URL, and appear a message like "Could not add recipe: "Field \"name\" is required", is possible import all validate data and leave the others blank? Or have a preview with all fields and fill only the one that wasn't possible to import by the URL.

Thank you,

**Comment by mrzapp** [comment]
@heliohenriques Unfortunalety, the name is quite a central piece of information we can't do without :sweat_smile: 

Which recipe is giving you this trouble?

**Comment by heliohenriques** [comment]
Hi,
Thank you for your quickly answer. 
All the receipts from this site https://lifestyle.sapo.pt/sabores/receitas

**Comment by mrzapp** [comment]
@heliohenriques Aha, it's the `<itemprop="name">` that doesn't have any content. I'll rename this issue to reflect that.

**Comment by mrzapp** [comment]
Related to #196

**Comment by heliohenriques** [comment]
Perfect. 
Thank you for the changes

**Comment by mrzapp** [comment]
Didn't quite do the work itself yet, so keeping this open :)

**Comment by mrzapp** [comment]
@heliohenriques the next release `v0.7.0` will fix this. However, the developers of the site you're using made a lot of mistakes in the markup, so the ingredients were not imported when I tried them.

Nothing we can do about that, sorry :/
