### ISSUE TITLE
"/" in recipe name leads to error

### ISSUE THREAD

**Issue by CSchlipp** [mrzapp/nextcloud-cookbook#205]
Importing a recipe with a name containing a "/" leads to an error. 

**Current Behaviour:**
During import, an additional subdirectory is created under the first one. Afterwards, the application faisl to store the json file and image in the created directories.

Test e.g. with: https://www.chefkoch.de/rezepte/2102041339230721/Gewuerzmischung-fuer-Haehnchen-Brathaehnchen.html

Seems like the paths are not sanitized correctly.

**Expected Behaviour:**
Replace/escape invalid characters when creating folders/files. Create only a single folder, not multiple ones and store the imported recipe in it.

**Environment:**
Version 0.6.3
Nextcloud 18.0.3

**Comment by CSchlipp** [comment]
Can confirm that the import is working in 0.7.1.
However, when editing the imported recipe, it cannot be saved while the "/" is in the recipe name.

**Comment by mrzapp** [comment]
@CSchlipp yeah, the fix was to disallow slashes, since filenames can't have them. We have to name the recipe files after the recipe itself, otherwise it'll be a bit hard to manage them without the app. Should we perhaps escape the slashes instead?

**Comment by CSchlipp** [comment]
@mrzapp However, during import, you have to escape the slashes anyways. Why not escape the characters after editing as well? That way, the recipe name can always stay as the original.

From security perspective, all input values of the application should always go through an escape-function. Then, this issue wouldn't occur at all. Otherwise, this issue might be only the tip of the iceberg w.r.t. to directory traversal attacks, SQL injection, Cross-Site-Scripting, ...

**Comment by mrzapp** [comment]
@CSchlipp you're right, I'll reopen the issue

**Comment by dm7ds** [comment]
Also a "/" in categoriename leads to an error "The page was not found"

**Comment by CSchlipp** [comment]
Slashes are now removed, but not escaped. Is this intended behavior?

I don't understand why you do not simply use [htmlentities](https://www.php.net/manual/de/function.htmlentities.php) for encoding incoming data before further processing it and [html_entity_decode](https://www.php.net/manual/de/function.html-entity-decode.php) before writing the values to form fields (for just showing them in the UI, you do not even need to decode). 
Here again, in terms of security, it always preferable to use a common built-in function to do such tasks instead of writing an own one...

**Comment by mrzapp** [comment]
@CSchlipp you're very welcome to submit your own patch, if you have a better idea. This project is fairly inclusive :)
