### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by senufo** [mrzapp/nextcloud-cookbook#21]
I would like to translate the application into French how to do?

**Comment by poltrian** [comment]
I woukd Like translate to German. I did it Into the Code Base. But Updates
overwrite it

senufo <notifications@github.com> schrieb am Mo., 5. Aug. 2019, 16:17:

**Comment by senufo** [comment]
Ok
Is it possible to adapt the code to make translations possible?

**Comment by mrzapp** [comment]
@poltrian The documentation about it is here, if you're interested in contributing this feature: https://docs.nextcloud.com/server/stable/developer_manual/app/view/l10n.html?highlight=translation

**Comment by poltrian** [comment]
hmm i'm not a programmer, could create the framework? And we nativ
speaker can do translations like l10n? I understand a little bit PHP
and how templates works, but that's  it
Am Montag, den 05.08.2019, 21:48 -0700 schrieb Jeppe Zapp:

**Comment by christianlupus** [comment]
I am just trying to put thngs together for translations.

**Comment by christianlupus** [comment]
For those willing to help with translations, please see PR #34. There is a draft version of documentation for controbuting by translating. As soon as it is merged, you should have a clear workflow to add new translations.
