### ISSUE TITLE
Empty the "image" field should not remove the image

### ISSUE THREAD

**Issue by vfauth** [mrzapp/nextcloud-cookbook#213]
Follow-up to #83.

When you add an image, either from Nextcloud or with a URL, it is cached to the recipe directory (full.jpg and thumb.jpg).

So, if you added it from Nextcloud, you can safely remove the original picture from the files app, Cookbook uses the cached one. Well, that's the intended behavior (see #64).

However, if you want to edit the recipe later, since the path in the "Image" field is not resolvable, the edit will fail. The only solution is to manually empty the "Image" field. I then expected Cookbook to use the cached file, but while the thumb is still displayed, the full image is not.

I see two separate issues there:

1. When the "Image" field is empty, full.jpg is not used.

2. When the recipe is created or edited, if the "Image" field is not a valid image, the save should not fail (well, that's my opinion at least).

Cookbook 0.6.4 on NC 18.0.4.

**Comment by mrzapp** [comment]
I've committed a patch that catches NotFoundException errors and lets you save the recipe anyway. This should solve the issue.

**Comment by vfauth** [comment]
Great, thank you!
