### ISSUE TITLE
Recipe renaming does not rename json file

### ISSUE THREAD

**Issue by vfauth** [mrzapp/nextcloud-cookbook#214]
When renaming a recipe, if the save fails (see #213 for example), the json file is still "Original name.json" (as expected) but the directory is renamed the new recipe name. It does not prevent the application from working fine, but the data is not in a very consistent state.

Cookbook 0.6.4 on NC 18.0.4.

**Comment by vfauth** [comment]
In fact, even when the renaming is successful, the json file is not renamed. So it's not really a bug.

**Comment by mrzapp** [comment]
We'll call it a mild bug, then :) Maybe we should just call the JSON file something generic, like `data.json`. What does @mcorteel think?

**Comment by mcorteel** [comment]
I'm very much in favor of a generic file name and I would suggest `recipe.json`.

**Comment by mrzapp** [comment]
@mcorteel alrighty, let's do that.
