### ISSUE TITLE
recipes "This page doesn't exist." since latest upgrade

### ISSUE THREAD

**Issue by yeupou** [mrzapp/nextcloud-cookbook#215]
Since upgrade to current version 0.6.4, all recipes lead to  

"Error
This page doesn't exist."

even though 
- they are properly listed
- the .json file seems to be in the proper location

Example with a newly create recipe:

![Screenshot_2020-05-04 Cookbook - qg($ Wr )}=%  uY](https://user-images.githubusercontent.com/1160681/80955415-94bfdc00-8dff-11ea-93c1-093fe5605179.png)

![Screenshot_2020-05-04 Cookbook - qg($ Wr )}=%  uY(1)](https://user-images.githubusercontent.com/1160681/80955436-9d181700-8dff-11ea-812a-4630f8d07189.png)

![Screenshot_2020-05-04 Recipes - Files - qg($ Wr )}=%  uY](https://user-images.githubusercontent.com/1160681/80955446-a0130780-8dff-11ea-8267-822fc0f9c98c.png)

![Screenshot_2020-05-04 test json - qg($ Wr )}=%  uY](https://user-images.githubusercontent.com/1160681/80955454-a1dccb00-8dff-11ea-8633-fc43ec1ec142.png)

**Comment by linuxsquad** [comment]
Same problem here, the cookbook plugin worked up to the update w/out flaw. BTW, great app!

**Comment by mrzapp** [comment]
@yeupou @linuxsquad odd, I'm unable to replicate this. Which version of NextCloud are you running? Also, what do you get when visiting the URL `https://mycloud[/index.php]/apps/cookbook/recipes/$RECIPE_ID`?

**Comment by yeupou** [comment]
- the url /apps/cookbook/recipes/$RECIPE_ID  (instead of apps/cookbook/#recipes/$RECIPE_ID) sprout "internal error"
- nextcloud version 17.0.5 (I use the gallery and last time I checked the proposed alternative since it's removal is not doing 1/3 of the job expected)

**Comment by mrzapp** [comment]
@yeupou first, please update to NextCloud 18. Then, if it still doesn't work, I'd like to see the log. @linuxsquad if you haven't, please also upgrade to NextCloud 18.

**Comment by yeupou** [comment]
Hi, 

I actually already upgraded to Nextcloud 18 and I had to revert to 17 due to the features regressions 
The nextcloud team seems to agree that these features regressions are a problem and normally it should be fixed or about to be https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32 nonetheless I am know not in a hurry to move to 18.

BTW The cookbook is listed to be working even with version 14 https://apps.nextcloud.com/apps/cookbook 
Do you made changes in last version that make it depends on Nextcloud 18?

**Comment by mrzapp** [comment]
@yeupou it's a bit optimistic of us to list it as working with 14, when AFAIK all the developers on this project use 18. We're a bit too short on resources to test against older NC versions, so I think we should just fix the information, so users won't accidentally upgrade.

Please revert to version 0.6.3 of the Cookbook app, if that worked for you.

**Comment by yeupou** [comment]
Yes, there was no problem with earlier version and Nextcloud 17.

Here's some log, clearly the issue seems to be a call to OC\\Files\\Node\\File::getCreationTime()


{"reqId":"a01v2cEfs9YyjCSzsipa","level":3,"time":"2020-05-05T10:50:50+00:00","remoteAddr":"XX.XX.XX.XX","user":"XXX","app":"index","method":"GET","url":"\/apps\/cookbook\/recipes\/2043432","message":{"Exception":"Exception","Message":"Call to undefined method OC\\Files\\Node\\File::getCreationTime()","Code":0,"Trace":[{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","recipe",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"2043432","_route":"cookbook.main.recipe"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"2043432","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"2043432","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/cookbook\/recipes\/2043432"]},{"file":"\/usr\/local\/share\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined method OC\\Files\\Node\\File::getCreationTime()","Code":0,"Trace":[{"file":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Service\/RecipeService.php","line":53,"function":"parseRecipeFile","class":"OCA\\Cookbook\\Service\\RecipeService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Controller\/MainController.php","line":179,"function":"getRecipeById","class":"OCA\\Cookbook\\Service\\RecipeService","type":"->","args":[2043432]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"recipe","class":"OCA\\Cookbook\\Controller\\MainController","type":"->","args":["2043432"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","recipe",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"2043432","_route":"cookbook.main.recipe"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"2043432","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"2043432","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/cookbook\/recipes\/2043432"]},{"file":"\/usr\/local\/share\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Service\/RecipeService.php","Line":953},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"17.0.6.2"}




{"reqId":"ADnkpvgwzN6MbxcXidLL","level":3,"time":"2020-05-05T10:51:53+00:00","remoteAddr":"XX.XX.XX.XX","user":"XXX","app":"index","method":"GET","url":"\/apps\/cookbook\/recipes\/1935175","message":{"Exception":"Exception","Message":"Call to undefined method OC\\Files\\Node\\File::getCreationTime()","Code":0,"Trace":[{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","recipe",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"1935175","_route":"cookbook.main.recipe"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"1935175","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"1935175","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/cookbook\/recipes\/1935175"]},{"file":"\/usr\/local\/share\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined method OC\\Files\\Node\\File::getCreationTime()","Code":0,"Trace":[{"file":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Service\/RecipeService.php","line":53,"function":"parseRecipeFile","class":"OCA\\Cookbook\\Service\\RecipeService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Controller\/MainController.php","line":179,"function":"getRecipeById","class":"OCA\\Cookbook\\Service\\RecipeService","type":"->","args":[1935175]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"recipe","class":"OCA\\Cookbook\\Controller\\MainController","type":"->","args":["1935175"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Cookbook\\Controller\\MainController"},"recipe"]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Cookbook\\Controller\\MainController","recipe",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"1935175","_route":"cookbook.main.recipe"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"1935175","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"1935175","_route":"cookbook.main.recipe"}]},{"file":"\/usr\/local\/share\/nextcloud\/lib\/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/cookbook\/recipes\/1935175"]},{"file":"\/usr\/local\/share\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/usr\/local\/share\/nextcloud\/apps\/cookbook\/lib\/Service\/RecipeService.php","Line":953},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"17.0.6.2"}

**Comment by yeupou** [comment]
I found out that, currently, "Photos" does not even show PNG images 
(and some Nextcloud dev seems not even convinced that some people are using PNG (ahem), not even mentioning the fact that *galleries* are not necessarily of Photos), so an upgrade is even more out of the picture, if I might say.

Any chance you look into the logs I posted to see whether the Cookbook can be made compatible with Nextcloud 17? If it is really about getting some file ctime, that should not be impossible but, granted, I did not dig to check if it involves a lot of work.

Thanks

**Comment by mrzapp** [comment]
@yeupou the offending line is here, then: https://github.com/mrzapp/nextcloud-cookbook/blob/fcac7d47072373b577918c51f0cbb4fccf8bdc8b/lib/Service/RecipeService.php#L967

Can you comment out that line in your local copy and see if that fixes it?

**Comment by yeupou** [comment]
Perfect!

Yeah, that fixes it.
Thanks!

**Comment by yeupou** [comment]
(and I found no issue with no value set, left in comment, after toying a bit)

**Comment by linuxsquad** [comment]
Confirmed the fix: commented the line out. Thanks

**Comment by Mannshoch** [comment]
Could you please update the app with the fix?

**Comment by mrzapp** [comment]
@linuxsquad @Mannshoch @yeupou this fix will be pushed with `v0.7.0`

**Comment by klink-mit-panzerslip** [comment]
Thanks a lot for your work.

**Comment by yeupou** [comment]
Thanks a lot for your work.
