### ISSUE TITLE
Editing Recipe Name Instead Duplicates It

### ISSUE THREAD

**Issue by vozeldr** [mrzapp/nextcloud-cookbook#22]
I confirmed this happens on both 0.1.7 and after upgrading to 0.1.8

1. Click the pencil icon next to a recipe in the list.
2. Change the name of the recipe (like just add a 2 at the end of the name).
3. Save the recipe.
4. Duplicate appears in the recipe list and the original is unchanged.

**Comment by mrzapp** [comment]
@vozeldr As a fix until it's patched, you can rescan the library in the settings

**Comment by mrzapp** [comment]
Presumably, this happens because the library cache doesn't remove the old entry when the recipe is edited. To fix  this, just make sure to rebuild any cached information regarding the given recipe by file id

**Comment by mrzapp** [comment]
@vozeldr I found the cause, it's because the JSON files are named after the title, so it actually duplicates the entire file. I'll work it out
