### ISSUE TITLE
Use long text input for Description

### ISSUE THREAD

**Issue by jotoeri** [mrzapp/nextcloud-cookbook#227]
- Use long text input for Description: Just like on the steps for preparation, a long text field for the description would be cool, allowing for new lines and more text.

Hey Jeppe,

thank you for this app! :) I even specifically installed a nextcloud now on my homeserver to use this app. 👍 :)
Three things i saw now on the first look, that would be cool enhancements of the app. I'll just write them in three separate issues.

Greets,
Jonas

**Comment by mrzapp** [comment]
@jotoeri this will be fixed with `v.0.7.0`

**Comment by jotoeri** [comment]
Nice, thank you! :) 🚀
