### ISSUE TITLE
Add fields - Description, URL, prepTime, cookTime

### ISSUE THREAD

**Issue by sir-indy** [mrzapp/nextcloud-cookbook#23]
I really like your cookbook app, I currently have my recipes as markdown files but your interface and layout is better.

To get all the detail for a recipe though, it needs to use the "description" and "url" field. The app uses the url to grab the recipe in the first place, and I find it useful to be able to refer back since I often change the recipe.
The description is in the example given on the https://schema.org/Recipe page, and would also help with issue #8.
CookTime and prepTime are nice to have as a quick reference, but can be kept optional.

I've never tried coding PHP before but I'll have a go at making these changes if you like.

**Comment by mrzapp** [comment]
@sir-indy thanks, I'm glad you like it :)

You're right, it currently only imports the bare minimum in order to standardise the JSON.

A pull request would be much appreciated, you can have a look at [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L62) method to add more fields to the JSON.

In order to render the information you need to change [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/templates/content/recipe.php) template.

In order to edit the recipes you need to edit [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/templates/content/edit.php) template.

**Comment by sir-indy** [comment]
Thanks for pointing me in the right direction for the changes, I'll have a go this weekend.
I've not contributed to an open source project before, though I've used lots, so I'm actually quite excited about helping!

**Comment by mrzapp** [comment]
I'm glad to hear it! Any little bit helps, and starting small is the way to go :+1:

**Comment by poltrian** [comment]
Nutritional information would be fine. i think its not a schema standard. but add by hand would be also fine.

**Comment by mrzapp** [comment]
@poltrian the nutrition field is standard, they can be added like ingredients :)

**Comment by sir-indy** [comment]
Ok, it took me a while to get set up with a fresh instance of Nextcloud to test, and get the hang of git and PHP, but I've got a working solution for description, url, prepTime and cookTime on a branch of my repo here: https://github.com/sir-indy/nextcloud-cookbook/tree/addfields

I'm not going to do nutritional info yet, might do that as future work.

Do I submit a pull request now?

**Comment by mrzapp** [comment]
@sir-indy go ahead, I'll review and merge it when I have time :)

**Comment by okcomputerik** [comment]
Very nice app indeed, highly appreciated!

Some recipes include Notes, which can sometimes be very important to the outcome and/or for variations to the recipes, so I would love to be able to import them into the cookbook, but I'm not sure it's a standard field in the recipe schema... If they are not, maybe they could be added by hand if there was a field for that?

Also, I like the daily dozen idea so, based on that, maybe it would be nice to have similar "flags" for things like: spicy, oven-required, gluten-free, vegan, vegetarian, raw, make-ahead (overnight), appetizer, etc.

I'm not a coder so I can't be of much help in that regard (although I will have a look at the instructions to introduce changes, but don't expect much), sorry. However, I can help with a Spanish translation if nobody is working on it yet.

Cheers!
