### ISSUE TITLE
Generated thumbnail image not respecting orientation of image

### ISSUE THREAD

**Issue by frlan** [mrzapp/nextcloud-cookbook#230]
The generated thumbnail for an picture is not respecting whether the image was rotated or not. 

This is how it looks like on the overview page:

![image](https://user-images.githubusercontent.com/1010248/83328339-87710280-a282-11ea-9ad0-8e6a912b9c3d.png)

However, the picture was rotated and exif.image.orientation set correctly.

**Comment by mrzapp** [comment]
@frlan the fix for this will be pushed with the `v0.7.0` update
