### ISSUE TITLE
Cookbook App does not load

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#235]
Hi, 

i just upgraded the app form 0.65 to 0.7 and after reloading the page it does not show anything - just a blank page !

My Configuration:

NC 19.0
PHP 7.3
SQLITE
![cookbok0 7](https://user-images.githubusercontent.com/9738727/83962274-759fe880-a89c-11ea-90ec-a7bb2230028a.png)

**Comment by mrzapp** [comment]
@hitam4450 You're right, the build script did not compile the JS. Hang on, making a new release

**Comment by mrzapp** [comment]
@hitam4450 should be fixed now, please try again.

**Comment by hitam4450** [comment]
Ok, app 0.71 loads...
