### ISSUE TITLE
App 0.71 does not show any existing recipe

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#236]
After upgrading the app to 0.71 the app loads, shows the existing recipes. after clicking on one of the recipes   error **Loading recipe failed
![cookbook0 71](https://user-images.githubusercontent.com/9738727/83963926-a5092200-a8a9-11ea-938d-7b0484cc30c1.png)
** occurs !

regards, hitam4450

**Comment by RobRobM** [comment]
I had the same problem. Turns out I now have a "Dutch" recipe folder which was selected. So for me (and hopefully for you) the fix was very easy. Just "settings" (bottom left) and select the right recipe folder.

**Comment by mrzapp** [comment]
@hitam4450 @RobRobM yeah, this was caused by #186. So if you hadn't configured your recipe folder explicitly before, it would be set to your language of choice.
