### ISSUE TITLE
app 0.71 rescan of reipe folder failed

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#237]
Hi, Version0.71 is just a  complete mess !

re scanning of the recipe folder does not show any recipe anymore !

better uninstall or test a new release much better and longer !

i am sick of the fact that software is maturing on users behalf !

regards, 4450

Ok, all of a sudden the app works !

**Comment by terencedesu** [comment]
Thanks for the quick fix. I was about to open an issue too. Mine didn't work on .07.0 but is working on 0.7.1

**Comment by mrzapp** [comment]
@hitam4450 just a few quick reminders:

1. The app is not at v1 yet, so it's beta software. Use at your own risk.
2. We are doing this in our spare time.
3. Nobody (in the entire world) owes you anything. 
4. I am not even using this app myself, as I'm trying to go more offline, so I'm maintaining this exclusively for your pleasure.

Next time, when you're reporting a problem, please keep your toxic attitude out of the description and stick to the facts. You're hurting morale more than you can imagine.

**Comment by mrzapp** [comment]
And thank you @terencedesu for being appreciative :)

**Comment by terencedesu** [comment]
@mrzapp, I would be interested to know what you are using for offline as I haven't found a satisfactory solution yet.

**Comment by mrzapp** [comment]
@terencedesu a paper notebook 😅

**Comment by terencedesu** [comment]
Nice. I'll have to give it a shot.

**Comment by mrzapp** [comment]
@terencedesu either that, or if you prefer storing stuff in markdown, CodiMD or Etherpad are pretty good options
