### ISSUE TITLE
Labeling of input boxes are inconsistent

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#238]
Hi, 
enclosed you'll find a screenshot of the inconsistency of the labeling of input boxes

I am using Deutsch / German as default language !

regards, hitam4450
![cookbook0 71b](https://user-images.githubusercontent.com/9738727/83971714-2f1eae00-a8dd-11ea-9c94-105baac7156f.png)

**Comment by mrzapp** [comment]
I'm pretty sure this will be solved when Transifex catches up, so keep an eye on it for new releases. I'll keep this issue open until you can confirm it's correctly translated

**Comment by mrzapp** [comment]
Same as #241
