### ISSUE TITLE
Unable to fetch data from websites with valid schema due to User Agent

### ISSUE THREAD

**Issue by tshoyo** [mrzapp/nextcloud-cookbook#24]
I attempted to add a recipe by URL, but the download method recipe failed as it was unable to get valid HTML from the website. When I checked the Nextcloud logs, I found this error message (with identifying information removed).
``` JSON
{
  "reqId": "someRequestID",
  "level": 3,
  "time": "2019-08-08T03:59:47+00:00",
  "remoteAddr": "00.000.00.00",
  "user": "someUser",
  "app": "PHP",
  "method": "POST",
  "url": "\/apps\/cookbook\/add",
  "message": "file_get_contents(recipeUrl): failed to open stream: HTTP request failed! HTTP\/1.1 403 Forbidden\r\n at nextcloudDirectory\/apps\/cookbook\/lib\/Service\/RecipeService.php#406",
  "userAgent": "Chrome User-Agent String",
  "version": "16.0.3.0"
}
```
The server at the given recipe URL returns 403 Forbidden most likely due to the lack of User-Agent header present with the `file_get_contents` method. When I used a request client for the recipe URL, I found that the website had the Cloudflare protection on it which explains why it would reject requests without a User Agent. 

Adding the a User-Agent header would make it possible to scrape all sites with valid schema behind reverse proxies designed to protect against DoS attacks. If you're too busy, I do not mind submitting a pull request!

**Comment by mrzapp** [comment]
@tshoyo thanks for digging into the problem and proposing a solution. A pull request would be much appreciated! :pray:

**Comment by tshoyo** [comment]
So, as I was adding in the header fix, the URL I was using was able to successfully fetch the html, but it kept throwing a type conversion error. I realized that the website uses a div element rather than an article element to host the actual recipe data. This would mean the html parser would need to be improved upon for this use case. 
However, I feel that using regex to parse html is not maintainable and would like to pursue a different route before messing with the current parser. It would be much better to utilize a DOM tree library to traverse the html, but I understand if there is a desire to keep dependencies to a minimum. This begs the question, is there any particular reason for fetching the recipe data server-side? 
Javascript has a built in DOM parser with the addition of JQuery to make traversal that much more trivial. We could just request the target URL with `$.ajax()` and then search the html for recipe data. This will increase the effectiveness of the parser without adding an additional library dependency. Worst comes to worst, we can fall back to the server-side parser if the Javascript one fails. Let me know what your thoughts are @mrzapp!

**Comment by mrzapp** [comment]
@tshoyo You're right, regex parsing is a huge pain, but trying to fetch the HTML with JSON alone would most certainly throw a CORS error. We could fetch the HTML using PHP and then parse it using JavaScript.

There is also the built-in XMLParser in PHP, which should work. I would have no problem including a library though, since it's such a big part of this app.

I don't have a lot of time to work on this, so I can't afford to be picky on how problems are solved. As long as we're not making the code base unreadable or screwing up the UI, I'll be happy to include any improvements in upcoming releases :)

**Comment by tshoyo** [comment]
Lol ah I am yet to learn my lesson about CORS after all the times it's bitten me in the butt. I will see if I can make the XML parser work out, otherwise, I might try a library that uses JQuery-like syntax.
