### ISSUE TITLE
App 0.71 - some recipes don't show the instructions

### ISSUE THREAD

**Issue by himpich** [mrzapp/nextcloud-cookbook#240]
Since the update, some recipes don't show the instructions anymore (recipe view & print view). In Editmode, the instructions are present. I'll attach an example json.

This is a recipe I entered after the update. The instructions are missing for some (not all!) older recpies, too. 
I tried google chrome (Windows) and google chrome (android). Both same result. 

Json File:
[recipe.json.txt](https://github.com/mrzapp/nextcloud-cookbook/files/4743079/recipe.json.txt)

Screenshot:
![missing instructions](https://user-images.githubusercontent.com/6817957/83981089-146b2a00-a91b-11ea-9b06-c376ff8f8fe4.png)

**Comment by mrzapp** [comment]
@himpich thanks for the report, a fix will be pushed soon
