### ISSUE TITLE
Moble Phone Firefox, no possibility to see catgorys and add Recips

### ISSUE THREAD

**Issue by poltrian** [mrzapp/nextcloud-cookbook#245]
On 6.x i was able to add Recipes and saw the category's. At 7.x both is not possible

**Comment by mrzapp** [comment]
@poltrian isn't it a general change in the latest NextCloud? I think you can just swipe from left to right to the the navigation menu. Or am I missing something?

**Comment by siccovansas** [comment]
On Android I can't add a recipe (since Nextcloud 19?) using either Firefox or Chromium. I also can't swipe the navigation menu open.

**Comment by RobRobM** [comment]
I don't have the navigation menu on the left any more as well.

**Comment by mrzapp** [comment]
#260 is more descriptive, so closing this one
