### ISSUE TITLE
0.7.2 opening recipe shows 'Loading recipe failed'

### ISSUE THREAD

**Issue by L0ric0** [mrzapp/nextcloud-cookbook#248]
**Description**
After upgrading from version 0.7.0 over 0.7.1 to 0.7.2 it is not possible to open any recipe. When trying to open a recipe a popup showing "Loading recipe failed" is opened.

**Reproduction**
1. try to open a recipe
1. see the error message

**Expected behavior**
Open the recipe

**Screenshots**

**Browser**
firefox

**Comment by mrzapp** [comment]
@L0ric0 do you have any log messages (either in the JavaScript console or the NextCloud log)? That would really help

**Comment by L0ric0** [comment]
if you mean the console opened with F12 the only line there is a 404 for `https://uraziel.de/nextcloud/apps/cookbook/api/recipes/214685` in the nextcloud log i haven't found anything

**Comment by malkavi** [comment]
I have the same issue since the 0.7.2 version
Request URL:https://xxxxxxx.xx/apps/cookbook/api/recipes/383517
Request Method:GET
Status Code: 404
Response: Payload: 383517

**Comment by L0ric0** [comment]
Request URL: https://uraziel.de/nextcloud/apps/cookbook/api/recipes/214685
Request Method: GET
Status Code: 404
Version: HTTP/2
Referrer Policy:no-referrer
Response: Payload: 214685

**Comment by knttr** [comment]
I've just updated to version 0.7.2 and have the same issue as described above.
A 'tail -f' on the Nextcloud log shows no entries when opening a recipe.

Firefox Console Network-tab output: 
Request URL: https://xx.xx.xx/apps/cookbook/api/recipes/242099
Request Method: GET
Status-Code: 404
Version: HTTP/2
Referrer Policy: no-referrer
Initiator: main.js:25

**Comment by mrzapp** [comment]
@knttr @L0ric0 @malkavi I can't reproduce this here, can either of you paste your recipe JSON here?

**Comment by malkavi** [comment]
Still not working with 0.7.3
File: Alioli sin huevo.json
```
{"name":"Alioli sin huevo","description":"","url":"http:\/\/www.directoalpaladar.com\/recetas-de-salsas-y-guarniciones\/alioli-sin-huevo-receta","image":"\/RecetasFotos\/aliolisinhuevo.jpg","prepTime":"PT0H0M","cookTime":"PT0H0M","totalTime":"PT0H0M","recipeCategory":"Salsa","keywords":"lacteo,salsa","recipeYield":4,"tool":["Batidora"],"recipeIngredient":["125 ml Aceite de Oliva","60 ml de Leche","1 pizca de Sal","1 diente de Ajo"],"id":"383094","@context":"http:\/\/schema.org","@type":"Recipe","recipeInstructions":[]}
```

**Comment by knttr** [comment]
Same here, still not working with 0.7.3
File: Klassische Scones.json
`{"@context":"http:\/\/schema.org","@type":"Recipe","image":"https:\/\/img.chefkoch-cdn.de\/rezepte\/3195661475664860\/bilder\/950787\/crop-960x540\/klassische-scones.jpg","recipeCategory":"Gro\u00dfbritannien & Irland","recipeIngredient":["250 g Mehl","1 EL Backpulver","1 EL Zucker","\u00bd TL Salz","60 g Butter , kalt","150 ml Vollmilch","1  Ei(er) zum Bestreichen"," Mehl f\u00fcr die Arbeitsfl\u00e4che"],"name":"Klassische Scones","description":"Klassische Scones - einfache und schnelle Zubereitung f\u00fcr leckere, klassische Scones, f\u00fcr 9 Portionen. \u00dcber 58 Bewertungen und f\u00fcr raffiniert befunden. Mit \u25ba Portionsrechner \u25ba Kochbuch \u25ba Video-Tipps!","recipeInstructions":{"0":"Reicht f\u00fcr ca. 9 Scones.","2":"Den Backofen auf 190 \u00b0C Ober-\/Unterhitze vorheizen. Ein Backblech mit Backpapier auslegen. ","4":"Das Mehl mit Backpulver, Zucker und Salz mischen. Die kalte Butter in St\u00fccken mit dem Finger unter das Mehl reiben, bis die Konsistenz von kr\u00fcmeligem Sand entsteht. Alternativ die Butter mit der K\u00fcchenmaschine in das Mehl einarbeiten. Das Mehlgemisch zur\u00fcck in die Sch\u00fcssel geben und in der Mitte eine Mulde formen. Milch in die Mulde gie\u00dfen und mit einer Gabel das Mehl unterheben, bis sich der Teig zusammenf\u00fcgt.","6":"Die Arbeitsfl\u00e4che leicht bemehlen, den Teig darauf geben und ebenfalls mit Mehl best\u00e4uben, damit beim Ausrollen nichts anklebt. Den Teig 3 cm dick ausrollen mit einem runden Keks-Ausstecher (6 cm) Scones aus dem Teig ausstechen.","8":"Die Scones auf das Backblech setzen und mit einem verquirlten Ei bestreichen. Im vorgeheizten Backofen auf der mittleren Schiene f\u00fcr 15 - 20 Minuten backen. ","10":"Die Scones schmecken bereits lauwarm herrlich.","12":"Hinweis: Die Zubereitung der leckeren Scones ist sehr einfach. Mehl wird mit Backpulver als Triebmittel gemischt und anschlie\u00dfend die kalte Butter eingearbeitet. Anschlie\u00dfend wird der Teig mit der Milch nur noch rasch zusammengef\u00fcgt und nicht geknetet. Dadurch erhalten Scones ihre typische Konsistenz."},"author":{"@type":"Person","name":"MrsFlury"},"publisher":{"@type":"Organization","name":"Chefkoch.de"},"datePublished":"2016-10-06","prepTime":"P0DT0H15M","cookTime":"P0DT0H15M","totalTime":"P0DT0H30M","recipeYield":1,"aggregateRating":{"@type":"AggregateRating","ratingValue":4.47,"reviewCount":58,"worstRating":0,"bestRating":5},"video":[{"@type":"VideoObject","name":"Video zu Klassische Scones","description":"Video zu Klassische Scones","thumbnailUrl":"https:\/\/api.chefkoch.de\/v2\/images\/crop-960x540\/videos\/2791\/preview\/org","contentUrl":"https:\/\/www.chefkoch.de\/rezepte\/3195661475664860\/Klassische-Scones.html","embedUrl":"https:\/\/video.chefkoch-cdn.de\/ck.de\/videos\/2791-video.mp4","uploadDate":"2016-10-06"}],"nutrition":{"@type":"NutritionInformation","servingSize":"1","calories":"1706 kcal"},"keywords":"","reviews":[{"@type":"Review","reviewBody":"Hallo, ich habe dieses Rezept nachgebacken und wir hatten unser erstes Scones-Fressfest, bei dem wir zu zweit die komplette Charge an einem Nachmittag vertilgt haben. Sehr empfehlenswert. Ei hatte ich nicht zuhause, es ging aber auch ohne.","datePublished":"2017-05-06","author":{"@type":"Person","name":"DuLauch"}},{"@type":"Review","reviewBody":"Vielen Dank f\u00fcr deine liebe R\u00fcckmeldung zum Rezept! Mmmh das Scones-Vertilgen am Nachmittag h\u00f6rt sich an einem perfektem Wochenende an :-) die muss ich auch bald wieder einmal zubereiten,\r\nliebe Gr\u00fcsse Doris","datePublished":"2017-05-06","author":{"@type":"Person","name":"MrsFlury"}},{"@type":"Review","reviewBody":"Hallo\r\nich habe dieses Rezept heute f\u00fcr meinen allerersten Sconesversuch benutzt. Allerdings hatte ich den Zucker vergessen, machte aber nichts, da ich Rosinen drin hatte. Es ging ganz einfach und schmeckte hervorragend. Das Mehl, , Backpulver und Butter habe ich mit dem Foodprocessor (Messer) zu richtigen feinkr\u00fcmeligen Konsistenz vermischen k\u00f6nnen. Dann alles in eine andere Sch\u00fcssel  gegeben und in die Mtte Milch gekippt, von der ich ein Drittel durch Buttermilch ersetzt habe. Eingeweichte Rosinen dazu und vorsichtig vermischt. Dann habe ich den Teig allerdings nicht mit einer Rolle ausgerollt sondern einen You tube Tip verwendet. Man sch\u00fcttet den Teig auf die gut bemehlte Arbeitsfl\u00e4che, legt die H\u00e4nde drum rum und formt den Kloss (ohne Kneten!) sch\u00f6n rund, dabei dreht man den Kloss immer etwas rund. Dann gl\u00e4ttet man mit etwas Mehl und bemehlten H\u00e4nden die Oberfl\u00e4che glatt kuppelartig ohne zu kneten. Man nimmt dann die Kuppel und dreht sie auf der Arbeitsf\u00e4che einfach auf den Kopf, damit hat man die superglatte Seite oben. Dann noch ganz sanft mit den Handfl\u00e4chen auf die gew\u00fcnschte Dicke dr\u00fccken ohne zuviel Luft aus dem Teig zu dr\u00fccken. Ausstechen und mit den Resten ohne zu kneten nochmal eine Kuppel zusammenschieben ,die man wieder umdreht und etwas platter macht und aussticht. In Ermangelung von clotted cream habe ich geschlagene Sahne und Creme Fraiche gemischt. Die Mengenangaben dieses  Rezeptes funktionieren wunderbar. Foto folgt. \r\nDanke sehr und lieben Gruss von Irene ","datePublished":"2016-12-01","author":{"@type":"Person","name":"-irene-"}}],"tool":[],"url":"https:\/\/www.chefkoch.de\/rezepte\/3195661475664860\/Klassische-Scones.html"}`

**Comment by knttr** [comment]
I just imported a recipe from another site and also created a new recipe. Both are shown as expected. All older recipes show "Loading recipe failed".

**Comment by baensch** [comment]
Hey Guys i ran into the same Issue. But I found a Small Workaround. Suddenly i have two Recipie folder. But one in German and one in english (my Nextcloud is in German) The English one is since install there. After i reinstalled the addon i got the German one and i copied the recipies in there and now i can access them again.

**Comment by malkavi** [comment]
> Hey Guys i ran into the same Issue. But I found a Small Workaround. Suddenly i have two Recipie folder. But one in German and one in english (my Nextcloud is in German) The English one is since install there. After i reinstalled the addon i got the German one and i copied the recipies in there and now i can access them again.

I can confirm this. I have nc in Spanish, copied the recipes to the new folder and now is working. I still have the old folder in English and duplicated recipes that I can't open.

**Comment by knttr** [comment]
My side is a little...complicated...

I usually run my NC account  in English. I am based in Germany and use a German OS with a German Firefox , which seems to make "Cookbook" appear as as "Kochbuch". My default Folder was "Recipes" - this is where I could see all the recipe.json files.

The other day I showed someone around NC and changed the language to German.
I did the "Cookbook" update to 0.7.2 while my account was still set to German. Since then the recipes were not loading.

The new recipes I added earlier on went to a folder called "Rezepte" (@baensch thanks for the heads up). I went back to the "Cookbook" App and found that my default recipe folder had been changed to "Rezepte". When I changed it back to "Recipes", I could view all my recipes again.

The question is why the update changed my default folder? Should the app not stick to the default folder under "Settings" no matter which language I use - even after an update?

**Comment by mrzapp** [comment]
All right, it seems you guys figured it out yourselves. This task caused the issue: #186

This was a necessary change, and you just need to move your recipes to the new folder, or change your storage folder back to "Recipes". Either solution will work.

Closing this issue now, as a similar one has already been resolved the same way.
