### ISSUE TITLE
Using cookbook without webpage

### ISSUE THREAD

**Issue by NathanInThailand** [mrzapp/nextcloud-cookbook#249]
I installed this tool hoping to use it as a way to digitize recipes that I have existing as paper cards. However as far as I can tell, the tool simply refuses to properly accept/display files that don't have a correct URL in the URL field. An option to turn that off would be much appreciated.

**Comment by mrzapp** [comment]
That is definitely not intended behaviour, it should work without URLs

**Comment by NathanInThailand** [comment]
I can create a recipe with the URL field blank without issue, but attempting to open the file in the cookbook plugin displays "Error This page does not exist." The file exists as a .json that I can open and edit on my nextcloud; but .jsons leave something to be desired when it comes to readability.

**Comment by mrzapp** [comment]
@NathanInThailand I can't reproduce this, at least not on the latest `master`. Can you paste your recipe JSON here?

**Comment by NathanInThailand** [comment]
After the update it appears it now functions correctly. Thanks
