### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by geeseven** [mrzapp/nextcloud-cookbook#264]
**Is your feature request related to a problem? Please describe.**

Currently, there is not an easy way to get data in or out of this app.  Not having a way to bulk add URLs is a barrier to entry and not having a way to export data is no-go for some.

**Describe the solution you'd like**

I would like to see an import and export feature.  The news app has import and export buttons within settings which I think is a good approach. I think the 'one item (URL) per line' would be a good format for the import and export files, but any format would be OK. 

**Describe alternatives you've considered**

For export, the follow one-liner does the trick but most people don't like using the terminal.
```sh
for URL in Recipes/*/*.json ; do cat "$URL"|jq --raw-output .url ; done
```

**Comment by mrzapp** [comment]
@geeseven the format we store the recipes in is basically already "exported", in that it's readable by any app that speaks schema.org. What exactly do you think is missing?

We already have an issue for importing multiple recipes #152

**Comment by geeseven** [comment]
> @geeseven the format we store the recipes in is basically already "exported", in that it's readable by any app that speaks schema.org. What exactly do you think is missing?

I was thinking about a situation if a user wanted to switching away from schema.org to bookmarks or a read it later application.  If you view this as out of scope, feel free to close this issue.


> We already have an issue for importing multiple recipes #152

Ah, I was not using the right keywords when searching.
