### ISSUE TITLE
Backslash for fractions not working in cookbook App

### ISSUE THREAD

**Issue by terencedesu** [mrzapp/nextcloud-cookbook#266]
**Description**
Imported recipe didn't have backslashes on fractions (so 1/2 tsp read 12 tsp). Editing the recipe to manually fix it showed up during editing but when saved it didn't show up

**Reproduction**
1. Import a recipe or create a new recipe and click checkmark to finish.
2. check any fractions written with backslash (1/2 reading as 12).
3. Edit recipe to fix backslash, click checkmark to finalize
4. Backslash disappears from recipe

**Expected behavior**
Backslashes in fractions
I checked the json files in a text editor and the escape characters are before the backslashes on imported files (I guess technically the escape character is a backslash and the character that isn't printing in my recipe is a forward slash. Sorry for not being clear) but for hand entered files the slashes are not written to the json file.

**Screenshots**
None
**Browser**
Brave and Chrome (same result with both)

The app is still awesome and I appreciate all the work you've done on it. If there is anything I can do to help with testing let me know.

**Comment by terencedesu** [comment]
My apologies. I just noticed this was an already opened issue.

**Comment by mrzapp** [comment]
Duplicate of #262
