### ISSUE TITLE
Loading recipe failed after update to 0.7.4

### ISSUE THREAD

**Issue by HassanMullah** [mrzapp/nextcloud-cookbook#269]
**Description**
Hello, I had on the NC19 under Cookbook version 0.7.2 in total 9 recipes. After updating to version 0.7.4 I added a new URL. Now I only have access to this one 10th recipe. With all 9 others the message "Loading recipe failed" appears

**NC Log**
[PHP] Error: DOMDocument::loadHTML(): Tag amp-install-serviceworker invalid in Entity, line: 8973 at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#424

**Browser**
Firefox - newst Version

**Comment by schnuddel** [comment]
After updating from 0.7.2 to 0.7.4 I noticed that the link to the recipes in settings was changed. After updating that link and rescanning the library I was able to access the recipes again.
So the bug seems to be with the update changing the path to the recipe files.

**Comment by HassanMullah** [comment]
perfect. thank you

**Comment by Moini** [comment]
I had the same issue, it suddenly used a translated folder name (Recipes > Rezepte). I moved my recipes from the Recipes folder to the Rezepte folder and it now finds them again.

**Comment by Moini** [comment]
How was this bug fixed?

**Comment by mrzapp** [comment]
@Moini it wasn't a bug, it was a transitional inconvenience.

The app is now doing what it should have been doing all along, so new users will not experience this problem. It would be perfect if we had built in some backwards compatibility for this, but it just isn't too big of a deal when users can fix it themselves, and we have more important issues to fix and features to implement.

Sorry for the inconvenience, but this app is just under development, and issues like that might still occur. The only thing I can guarantee is that we will never introduce changes that result in data loss.

**Comment by Moini** [comment]
Didn't realize this was still in beta, thanks!
