### ISSUE TITLE
Failed test in travis

### ISSUE THREAD

**Issue by christianlupus** [mrzapp/nextcloud-cookbook#27]
I just saw that my PRs cause travis CI to report errors. Are there no errors for your repo? I get even error when I simply fork your current master.

So either there is something really weird going on here, you are nor using travis, or there are bugs in the code that should be removed.

If you do not use travis or the error is known I suggest that you update your test cases such that travis does not error but give a warning instead or so.

**Comment by mrzapp** [comment]
@christianlupus never used travis, I'll look into it

**Comment by mrzapp** [comment]
Closing as I don't have much time to look into this, and I can't see any way this hurts the end-user experience.
