### ISSUE TITLE
Can't reach the recipe on website

### ISSUE THREAD

**Issue by Hubby972** [mrzapp/nextcloud-cookbook#270]
**Description**
Try to download recipes from verified website (by cookbook user) but it failed on every website with the error below.(see attached pictures from the message error on the app and the log error from nextcloud)
I have a nas qnap TS-453A with Nexcloud 19.0.1

**Reproduction**
1. Go to 'the app in nextcloud.'
2. paste the internet adresse from verified website (by cookbook user) in the url box in the app
3. See error : (see below)
4. Nextcloud log error

**Expected behavior**
download the recipe from verified website (by cookbook user).

**Screenshots**
<img width="1259" alt="Screenshot_1" src="https://user-images.githubusercontent.com/67062690/84914017-6b12f980-b0bb-11ea-878b-0c8449d89353.png">
<img width="1628" alt="Screenshot_2" src="https://user-images.githubusercontent.com/67062690/84914037-72d29e00-b0bb-11ea-8b3e-b050953f1cab.png">

**Browser**
firefox 77.0.1

**Comment by mrzapp** [comment]
@Hubby972 I can't reproduce this, when I import the recipe from https://www.hellofresh.co.uk/recipes/tandoori-hasselback-chicken-5ed019f25a2c64346d2b6fbc, it works fine.

You might have another problem on your end, perhaps firewall or DNS related? But the address in your example definitely works in the app.
