### ISSUE TITLE
Moving Ingredients & Instructions lead to loss

### ISSUE THREAD

**Issue by dm7ds** [mrzapp/nextcloud-cookbook#273]
I added new instructions and ingredients and moved them up.
Instructions: All existing items will be deleted wich are below the moved one.
Ingredients: The moved item will be deleted.

The java console does not throw any errors.

**Comment by mrzapp** [comment]
@sam-19 would you mind looking into this one?

**Comment by sam-19** [comment]
Hey! I cannot replicate this bug, but I now notice that when adding and moving ingredients, the ingredients that are moved will be lost. This bug did not come up in my initial testing, and I have no idea when it could have been introduced.

**Comment by sam-19** [comment]
Okay, this had got to be the easiest bug in my life to fix, pushing a merge request in a sec...

**Comment by dm7ds** [comment]
Thank you (all) for this great app and support! Happy that this was an easy one :)
