### ISSUE TITLE
Instructions not displayed for my recipe

### ISSUE THREAD

**Issue by Moini** [mrzapp/nextcloud-cookbook#274]
**Description**
I created a recipe with all fields filled in.

**Reproduction**
Import this recipe:
[Rosa Holunderblütengelee mit Melisse und Minze.zip](https://github.com/mrzapp/nextcloud-cookbook/files/4810607/Rosa.Holunderblutengelee.mit.Melisse.und.Minze.zip)

Select it to display it. The instruction steps are missing.

**Expected behavior**
All parts of the recipe should be shown.

**Screenshots**
![Bildschirmfoto_2020-06-22_02-31-26](https://user-images.githubusercontent.com/3240233/85238774-7f932100-b430-11ea-8ac4-56e07430312b.png)

**Browser**
Firefox 77.0.1

**Comment by mrzapp** [comment]
@Moini works for me 
![image](https://user-images.githubusercontent.com/2747428/85370678-5dcc9380-b52f-11ea-9afb-a7bb1fa557ac.png)

Are you on the latest versions of NextCloud and the Cookbook app?

**Comment by Moini** [comment]
@mrzapp Thanks, the update from 18.05 to 18.06 did the trick.
