### ISSUE TITLE
min PHP version missing in dependencies

### ISSUE THREAD

**Issue by IzzySoft** [mrzapp/nextcloud-cookbook#282]
**Description**  
In `appinfo/info.xml`, there's no mention of the min PHP version required. This just broke my install on a Linux Mint 18 with Nextcloud 15 (Mint 18 only provides PHP7.0 – but it's a LTS still supported until 2021; due to some other things, I cannot yet update to Mint 19 or 20 yet, thus not to PHP7.1+, thus not to Nextcloud 16+ etc). As it's not pointed out, my Nextcloud just updated Cookbook to v0.7.6 – which led to a 500 server error and the app being disabled.

I was able to fix that by downgrading to v0.6.3 (replacing `apps/cookbook` and executing `update oc_appconfig set configvalue='0.6.3' where appid='cookbook';` in the database, followed by a `sudo -u www-data php occ app:enable cookbook` from within the nextcloud directory where `occ` resides – in case someone else falls into the same trap).

**Reproduction**  

1. Start with cookbook 0.6.3 or below on a server running PHP < 7.1
2. Go to "Apps"
3. Hit the update button for the Cookbook app
4. try to open your cookbook
5. See error

**Expected behavior**  
Nextcloud would not offer to update beyond v0.6.3 (which AFAIK is the last version working with PHP7.0 – v0.6.5 does not; I didn't try v0.6.4 so please let me know before I break things again :wink:)

**Screenshots**  
n/a

**Browser**  
n/a

**Suggestion**  
Add the following inside `appinfo/info.xml`:

```xml
    <dependencies>
        <php min-version="7.1" />
    </dependencies>
```

(of course with the correct PHP version in there – I don't know whether it's 7.1 or 7.2)

If Nextcloud doesn't honor that (which seems to be the case, as it also updated another app having this dependency declared), that's to be solved there. How far they'd backport his is a different issue of course.

**Comment by IzzySoft** [comment]
Thanks! And am I correct that v0.6.3 is the last one supporting PHP7.0?

**Comment by mrzapp** [comment]
@IzzySoft if that's the last version that worked for you, then it seems so :) None of us devs have had this problem, so we didn't pay much mind to which features of which exact PHP version we were using.

**Comment by IzzySoft** [comment]
OK, then I try the 0.6.4 on one of my other instances where I can simply remove it afterwards should it fail (I know 0.6.5 does not work with PHP7.0, but skipped 0.6.4 when "running down"). Hopefully I can upgrade soon.

Btw, as it might be of interest to you: following my CallOut, there's now an Android companion app available: [Nextcloud Cookbook](https://apt.izzysoft.de/fdroid/index/apk/de.micmun.android.nextcloudcookbook) is currently in my F-Droid repo (as it's considered "beta"), but already running pretty stable. It's a viewer only, and relies on the data having been synced to the device by other means (e.g. via the Nextcloud Android app). Works well, you might wish to mention it. An update is due this evening (v0.30.0). Once its author declares it "stable", it will move to F-Droid.org.

**Comment by mrzapp** [comment]
@IzzySoft cool, did you mention it on the issue? #207

**Comment by IzzySoft** [comment]
Just done, thanks for the hint!
