### ISSUE TITLE
Add sections to ingredients

### ISSUE THREAD

**Issue by Helium314** [mrzapp/nextcloud-cookbook#285]
Often recipes are composed of several parts, e.g. dough and filling. These parts typically have separate sections in the ingredient list.

When importing recipes, these sections get merged, and I found no way of adding them manually (except by inserting "fake ingredients").
Would it be possible to add this feature to the app?

Sorry in case this is already requested, I didn't find related issues.

**Comment by sam-19** [comment]
There is a way to add kind of sub-headers to the ingredient list by starting the line with "## " (for example "## Dough"). I think these are still treated just like any ingredients in the JSON file, but at least there's a way to visually separate them before a more robust feature is available. You still have to add these sub-headers manually, though.

**Comment by mrzapp** [comment]
We've been other this a few times before, and it's not supported by schema.org, so we're stuck with custom headings like what @sam-19 suggested for now.
