### ISSUE TITLE
Imported recipes uses original link for image

### ISSUE THREAD

**Issue by JoshuaPettus** [mrzapp/nextcloud-cookbook#287]
I think this is just an oversight.  When I use cookbook's import recipes from a website.  It does the import as expected but when I go edit the recipe, I see for the image it links to the original image on the original site and not the image that was imported into the nextcloud recipe folder.   This is problematic as If the recipe were pulled from the site the image would go.  Not to mention it's rather ugly for my nextcloud to be pulling from all these sites when it can very well host the image itself and already is :)

**Comment by Teifun2** [comment]
I dont think that is correct but i did see something similiar.

in the .json file there should be 2 image tags. Once `image` which points to the original image of the recipe. and then `imageUrl` which is the location of the image in your nextcloud instance. To my knowledge the `imageUrl` is used. Can you confirm this?

Maybe I'm wrong!

**Comment by mrzapp** [comment]
@JoshuaPettus the original URL is maintained as a string in the JSON, but the actual image you're seeing when opening the recipe is the locally stored one. If you delete the local image by accident, the app will try to fetch it from the original URL again. That's why it's retained :)

**Comment by JoshuaPettus** [comment]
Ah I see, thank-you for checking that!
