### ISSUE TITLE
duplicate serving

### ISSUE THREAD

**Issue by cloud2018** [mrzapp/nextcloud-cookbook#30]
text "servings" is duplicated, since PR "added support for translations" 

![Cookbook   Nextcloud](https://user-images.githubusercontent.com/34692335/62783119-06126e80-babc-11e9-824f-1a87f55181e5.png)

https://github.com/mrzapp/nextcloud-cookbook/blob/c25eed7841aa571870dd09fe7d7b35c511e7de21/templates/content/recipe.php#L10-L11

@christianlupus

**Comment by christianlupus** [comment]
Uups. Yes that is a bug. Sorry for that. The first line you mentioned must be dropped.
