### ISSUE TITLE
Can not manually create a reciepe

### ISSUE THREAD

**Issue by poltrian** [mrzapp/nextcloud-cookbook#32]

**Comment by poltrian** [comment]
If i click Save to create a recipe it shows a message "can not update recipe. Cookbook 0,19

**Comment by mrzapp** [comment]
@poltrian You're right, fixed in store now

**Comment by JimmyKater** [comment]
oopps commented about that already here:
https://github.com/mrzapp/nextcloud-cookbook/issues/10#issuecomment-539464902

**Comment by poltrian** [comment]
yes manually not work (again), but it was fixed before, the is a new
bug
Am Dienstag, den 08.10.2019, 04:14 -0700 schrieb JimmyKater:
