### ISSUE TITLE
Reference local photos in recipe

### ISSUE THREAD

**Issue by Popyllol** [mrzapp/nextcloud-cookbook#37]
Hi!
First of all: I like it!

Is there a way to reference photos out of the local nextcloud?

Greetings,

   Lars

**Comment by mrzapp** [comment]
That does not seem to work, no. An good feature would be to be able to pick it via the file browser, too.

**Comment by mrzapp** [comment]
@Popyllol are you able to look into the scripting side of this yourself and make a pull request?

**Comment by Popyllol** [comment]
> @Popyllol are you able to look into the scripting side of this yourself and make a pull request?

I fear I am too stupid to do that :-}

**Comment by mrzapp** [comment]
@Popyllol OK, then I'm closing this issue, as it hasn't been a requested feature before. The only way I can think of doing this currently is by making a photo on your NextCloud public first and then copying its URL into the recipe's image field. You can make it private again after you load the recipe once.
