### ISSUE TITLE
Instructions  not shown and can not add by hand

### ISSUE THREAD

**Issue by poltrian** [mrzapp/nextcloud-cookbook#4]
Instructions from german online recipes not shown and i can  not add them by myself. The + is not working.

But i like the idea very much!! And it looks great. So i would be happy the project will go ahead!

Good luck

**Comment by mrzapp** [comment]
Yeah, the flow for manually adding recipes has not been properly started. I'll try to find some time for it soon.

Which website didn't work for you?

**Comment by poltrian** [comment]
Hi, 
with the new version not instructions shows and i can not edit Ingredients and Ingredients.
https://www.rewe.de/rezepte/bier-frikadellen-burger-pilz-zwiebel-geroestl/
https://www.lecker.de/gemuesetortilla-73731.html
https://www.lecker.de/omas-hackbraten-35095.html
https://www.chefkoch.de/rezepte/643101165400472/Ofenkartoffeln-mit-Pfifferlingen.html
array_filter() expects parameter 1 to be array, null given at /var/www/xxxxt/html/nextcloud/apps/cookbook/lib/Service/RecipeService.php#152
str_replace() expects at least 3 parameters, 2 given at /var/www/ubuntuone.ddns.net/html/nextcloud/apps/cookbook/lib/Service/RecipeService.php#78

**Comment by mrzapp** [comment]
BTW, to edit ingredients you need to click the edit icon in the recipe list
