### ISSUE TITLE
Features wanted: Wider recipe pane, edit button on each recipe & reset search filter

### ISSUE THREAD

**Issue by okcomputerik** [mrzapp/nextcloud-cookbook#41]
You've done a fantastic work with this app, and I'm truly grateful!

That said, I can think of three UI/UX enhancements that would make my life easier, and hopefully others too? Nothing urgent or important, but nice to have. (Do let me know if I should open a separate issue for each of them.)

1. I would like the recipe title pane on the left side to be wider or for the text to wrap around, so that similar (and long) recipe names are easier to distinguish from one another. Currently, the text seems to be limited to 24 characters, so maybe it could be extended to 40-50 characters?

2. I sometimes have trouble finding the name of the recipe I'm currently reading on the left pane when I want to edit it, scrolling across dozens or hundreds of recipes, so it would be very helpful to have an "Edit" button on each recipe page (on the image, top-right corner, or next to the title, for instance), to access the edit page directly.

3. A button to reset the search filter.

Cheers!

**Comment by mrzapp** [comment]
@okcomputerik  Certainly, those would make life easier, I've thought about 2 of those myself at some point. The recipe title pane is limited by NextCloud defaults, so we might have to think about another way to represent the library. Perhaps as a grid in the main view.

**Comment by okcomputerik** [comment]
That was quick! I just updatee to 3.0 and everything seems great. Thanks a bunch!

**Comment by okcomputerik** [comment]
@mrzapp Just a comment regarding the reset search filter, which otherwise works great:

When I type in something in the search field I automatically hit enter to start the search but when I do this in the cookbook, it resets the filter instead of actually doing the search. You have to click on the magnifying glass icon for the search to begin. I don't know whether it was intended this way or not, but it seems counterintuitive to me. It's not a big issue considering both the search and reset functionalities are there, but just wanted to let you know.

Cheers!
