### ISSUE TITLE
Missing files in tar files release v0.3.2

### ISSUE THREAD

**Issue by senufo** [mrzapp/nextcloud-cookbook#48]
I wanted to install version v0.3.2 to have the French translation but it does not work.
After searching, the release v0.3.2 in version tar.gz does not contain the translation files. It misses the translationsfiles directory.
In the zip version of release 0.3.2 these files are present.
I tried to manually install the zip version but it does not work

**Comment by christianlupus** [comment]
You need not the `translationfiles` folder but the `l10n` folder. This should be generated during release but was forgotten in the release script. The PR #49 should remove this bug and in the next release the localization should be present.
Temporarily, you could add the content of [this file](https://github.com/mrzapp/nextcloud-cookbook/files/3570845/l10n.tar.gz) to the cookbook folder in your nextcloud installation. However this might break auto-installation, so undo before updating cookbook app.

**Comment by senufo** [comment]
Thanks work fine with l10n.tar.gz
There are two untranslated fields in the form to create a recipe.
_Prep Time_ and _Cook Time_
They are not in .po files

**Comment by mrzapp** [comment]
Thanks @christianlupus, a new release is ready now
