### ISSUE TITLE
Add wildcats for Search

### ISSUE THREAD

**Issue by poltrian** [mrzapp/nextcloud-cookbook#5]
Thanks again for your great work. 

Could you please add wildcats? I try to find a receipt, but only the full name will find one. But i try to find any Cake, nothing is shown.

Thanks..

**Comment by mrzapp** [comment]
The search is based on keywords only at this point, so unless your recipe is tagged with "cake", it won't show up when searching for that.

**Comment by mrzapp** [comment]
Closing as fuzzy search is not something I have enough time for at the moment.

**Comment by christianlupus** [comment]
I just hacked something in PR #12. Maybe this can be useful here.

**Comment by mrzapp** [comment]
@christianlupus it seems to work well, so merging it

**Comment by christianlupus** [comment]
See also #1293
