### ISSUE TITLE
Overview of recipes shows entries from any user

### ISSUE THREAD

**Issue by LunaticTazz** [mrzapp/nextcloud-cookbook#50]
Hi,
I have noticed a behaviour, that as soon as you open the app "cookbook", you will always see all the recipes of the last user who refreshed his/her library. Every user has to rescan his recipes once he/she enters the app which then starts the cycle again.
This might have to do with caching or my server configuration, but I think the easiest way out would be an automated rescan with the start of the app. Either this, or a database which is user specific.

Let me know if you experience any similar behaviour.

Nextcloud Version 15.0.11
Cookbook Version 0.3.3
PHP 7.0.33-0+9deb9u3
Tested with Firefox 68.0.2 and Chromium 76.0.3809.100

**Comment by mrzapp** [comment]
It's an oversight on my part, we need to add a "user id" column to the database schema and only let the current user change those records

**Comment by mrzapp** [comment]
@LunaticTazz a new release, v0.4.0 is up now. You will have to rescan the library (Settings > Rescan library) for every user to see the recipes again
