### ISSUE TITLE
It would be useful to be able to group multiple ingredients together under a common heading.

### ISSUE THREAD

**Issue by dmbreakey** [mrzapp/nextcloud-cookbook#53]
I currently just create dummy entries, usually in ALL CAPS to help it stand out, but https://stackoverflow.com/questions/46038625/schema-org-for-complex-or-multi-part-recipes suggests a method of structuring multiple recipes into one using the [schema.org Recipe](https://schema.org/Recipe) schema; could something similar be used?

I see this commonly used to group components of a more complex recipe together; for example [Lemon Meringue Pie: Reloaded](https://www.cookingchanneltv.com/recipes/alton-brown/lemon-meringue-pie-reloaded-5538372) which is basically a collection of three "independent" recipes that combine to make a single final product.

He also uses the same structure to identify required/recommended hardware, which is convenient.

It's a pity the site doesn't appear to use the Schema.org markup themselves, as that would probably be a useful starting point for a possible structure.

Sure I can just create three separate recipes, but that's awkward and vaguely unsatisfying.

I might try to take a crack at this myself, but I'm minimally experienced with PHP and present coding standards.

**Comment by mrzapp** [comment]
@dmbreakey This sounds like a valuable addition, I would be happy to merge it. It would mainly be a frontend challenge, although some changes would be required in [this](https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L62) service method.

To be honest, I'm not a master PHP programmer myself, and although I'm usually quite meticulous about standards, I really don't care much for the unique snowflake PHP is in this regard :D

If you've got something to add, just have a crack at it, and we'll merge it if it works and doesn't do any harm to the security or UX.

**Comment by dmbreakey** [comment]
No idea yet how to implement it, but I've been thinking about the UX. The following assumes we can devise some way of encoding this into the schema.org markup that won't break things.

I navigate using the keyboard extensively, so I'd prefer to see a navigation pattern that facilitates this. Also, I think the UX should be tailored for each category of data (ie: ingredients vs. steps).

For INGREDIENTS I think we should preserve the existing behavior as much as possible; simply add a toggle of some kind for each entry that identifies it as a heading, rather than an ingredient. When a new entry is created, the toggle should be **unset**, to preserve the existing behavior. An entry should only ever be treated as a heading when the user _explicitly_ sets it as such, either via mouse or (preferably) keyboard shortcut.

As for actually marking it up in the JSON, perhaps a simple "H:" at the head of each entry? That should allow for a simple enough change that also will still work acceptably well with other JSON parsers. IE, something like: "recipeIngredient": [ "H:Group 1", "Ingredient 1", "H:Group 2", "Ingredient 2" ]

For STEPS, I think we need something a bit more comprehensive, but still following a similar pattern to above. The key change would be:

1. The number of potential states needed.
2. The abbreviations used to mark them up.

At a minimum I think we might need:

- "CN:" for "Cook's Note" type entries (eg: Food Network commonly uses these to highlight important extra information).
- "H:" for "Heading", with similar use and formatting as for INGREDIENTS, above.

Of course, this is just brainstorming right now, so if anyone has a better idea, I'm all ears.

Also, I assume this would require changes in both back- and front-end (ie: JavaScript) pieces.

**Comment by dmbreakey** [comment]
After reviewing the [schema](http://schema.org/Recipe), it _appears_ there's nothing we can do for ingredient grouping except maybe the hackish solution I've proposed.

For recipe steps, fortunately, the schema is more accommodating; the [step](http://schema.org/step) property allows for a great deal of flexibility that looks like it could be adapted into groups, group headings etc.

One thing I did notice, though: the schema does allow a [tool](http://schema.org/tool) which obviously can be used to identify any required tools. One thing I wasn't able to figure out is how to mark a tool as optional.

With that in mind, is it allowed to just use a different property, instead of the plain [text](http://schema.org/Text) that _recipeIngredient_ officially supports? Can we at least have multiple _recipeIngredient_ lists?

Adopting the _tool_ property would be even better, I think, but I'd be worried about breaking compatibility. Or maybe the [supply](http://schema.org/supply) property? Actually that probably _would_ be the better (closer to official, not to mention accurately reflecting what an ingredient actually **is**) alternative. But again, compatibility.

**Comment by dmbreakey** [comment]
Ok, I just realized [recipeIngredient](http://schema.org/recipeIngredient) is a refinement of [supply](http://schema.org/supply), so can't we leverage that?

**Comment by mrzapp** [comment]
@dmbreakey I agree this is frustrating, but I actually think your manual solution is currently the only way.

Schema.org is quite clumsily put together, but it's a very high priority for this app to stay compliant with the rest of the world. 

I don't really want to, but I'm closing this issue for now, as this doesn't seem achievable.

**Comment by christianlupus** [comment]
I am sorry to maybe be a bit stupid...
According to my understanding of [recipeInstructions](http://schema.org/recipeInstructions) the instruction field is either a plain text, a `Creative work`, or a list of [HowToSteps](https://schema.org/HowToStep) or [HowToSections](https://schema.org/HowToSection). Especially the `HowToSection` seems to consist  of `HowToStep` objects. This might allow us to group the parts together.

Nevertheless, I have to admit, that I do not get the current storage (as implemented in the latest release) to correlate with this definition of `recipeInstructions`. The JSON stored is an object with the keys the indices of the instruction and the value a string as far as I understand it. This seems inconsistent with my understanding of the standards quoted above.

Sorry, if I am dump of if I oversee obvious things. Please tell me so, if this is the case.

**Comment by mrzapp** [comment]
@christianlupus this issue is about the `[recipeIngredients](http://schema.org/recipeIngredient)` field, not the `recipeInstructions` field. Unfortunately, it only expects `Text`, which is infuriatingly limiting :D

But you're right, the current storage of `recipeInstructions` should be changed, as discussed in [this issue](https://github.com/mrzapp/nextcloud-cookbook/issues/47). I haven't had much time to get into it myself, but it doesn't look like a big change.
