### ISSUE TITLE
Shared Cookbook not possible

### ISSUE THREAD

**Issue by marcelcremer** [mrzapp/nextcloud-cookbook#54]
Hi there,

I just tried the cookbook extension and it's absolutely awesome! Unfortunately I tried to share the recipes with my wife, but it's not possible to share the files for 2 ppl.

The error message is:

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_cookbook_recipes" ("recipe_id", "name", "user_id") VALUES(?, ?, ?)' with params [430, "15-Minuten-Pfanne", "yael"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_cookbook_recipes_pkey" DETAIL: Key (recipe_id)=(430) already exists.
```

As I'm not a php developer but a dev myself, I tried to understand where the issue is. It looks like the indexer function in

https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Db/RecipeDb.php

Line 159

retrieves the file id and tries to store the file afterwards using this id. However, as the id has a primary_key constraint on it which doesn't include the user name, and the first user already reserved this id, the db complains about it.

The Database I used is PostgreSQL.

As I said, I'm not a PHP dev so unfortunately I can't create a PR, but maybe this information helps a bit to solve this issue.

Cheers
Marcel

EDIT: It looks like when the constraint is dropped, everything works out just fine, so this might be a PostgreSQL specific problem.

**Comment by mrzapp** [comment]
@christianlupus Yep, I needed to remove the primary key constraint on the recipes table, since entries are no longer unique, but replicated for each user. The change will get published in a few minutes.

**Comment by marcelcremer** [comment]
@christianlupus Yes the user was ```yael``` and the first user adding the recipes was the admin user.

You guys are super fast! :)

**Comment by mrzapp** [comment]
@marcelcremer You managed to stumble upon an error just hours after it was introduced, so right back at you :D Thanks for the report
