### ISSUE TITLE
Shared recipes are stopped being shared, once the file is edited

### ISSUE THREAD

**Issue by LunaticTazz** [mrzapp/nextcloud-cookbook#57]
Description: Once a shared recipe is edited by the original creator, the share is lost. If someone the recipe is shared with edits the file, the share is lost, too, but a new file is created instead. Two instances of the same recipe exist now. I think this might partly coincide with #33 as files are not edited for nextcloud but rather deleted and recreated.
Maybe related to issues #54 and #50, too.

Solution ideas: Maybe this behaves as wanted, once #33 is implemented, maybe an additional share button from inside the cookbook app might work, so that cookbook works the shares and keeps them alive.

**Comment by mrzapp** [comment]
@LunaticTazz Are 2 actual copies of the recipe JSON file created, or is it just duplicated in the list overview?
