### ISSUE TITLE
Undefined variable: result at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#102

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#60]
I get a lot of error messages when adding recipes from https://www.chefkoch.de/

The error: Undefined variable: result at /var/www/nextcloud/apps/cookbook/lib/Service/RecipeService.php#102

Here are three recipes for testing:
https://www.chefkoch.de/rezepte/1844061298739441/Mozzarella-Haehnchen-in-Basilikum-Sahnesauce.html
https://www.chefkoch.de/rezepte/454281138117689/Penne-mit-Haehnchen-und-Champignons.html
https://www.chefkoch.de/rezepte/541521151483685/Super-schnelle-Himbeertorte.html

**Comment by mrzapp** [comment]
Thanks for reporting this
