### ISSUE TITLE
Feature wanted: Edit Image

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#61]
The section that is chosen for pictures and displayed in the app is not always good. For example, with this recipe:

https://www.chefkoch.de/rezepte/541521151483685/Super-schnelle-Himbeertorte.html

It would be nice if you could move the section or has significantly more influence on the pictures.

Are actually local images from the Nextcloud supported? This would also be desirable.

Are the pictures retrieved from the website again and again? I only found the link to the image in the json file. So the recipe would break if the original image / recipe would be deleted once? The storage of all recipe data in own Nextcloud would be useful.

**Comment by mrzapp** [comment]
@xsus95 I will be working on storing the images locally instead of just caching them, as we're currently doing. This will enable file upload/selection too. 

Do you have a suggestion for where else to display the image?

**Comment by xsus95** [comment]
I am not referring to the positioning of the images. I'm addressing the way the images are being cut out. Sometimes the original image gets unfavorably cut off.
It depends on the source. It would be great if you'd be able to influence the pictures sectioning.

**Comment by mrzapp** [comment]
Yeah, I suspected you might be talking about that, so i removed the cropping altogether, which I think looks better. Will that suffice?

**Comment by xsus95** [comment]
Yes, the solution is much better. Thanks!
