### ISSUE TITLE
Feature: Including own pictures, grouping and sorting

### ISSUE THREAD

**Issue by Githopp192** [mrzapp/nextcloud-cookbook#62]
i would be great to upload own pictures of the Recipes, would be fine, too .. if you could make Directories .. where you could group the recipes .. an export/import function (including the pics) would be great. Thanks for your efforts .. do appreciate.

**Comment by Githopp192** [comment]
yes .. and of course .. having those things into the Nextcloud app would also be great .. 
it's almost Christmas .. so we can still wish :-)

**Comment by mrzapp** [comment]
I will be working on local image support soon :) If you have any other explicit feature requests, please post them as individual issues.
