### ISSUE TITLE
Local image support

### ISSUE THREAD

**Issue by mrzapp** [mrzapp/nextcloud-cookbook#64]
We should restructure the storage so that every recipe gets its own folder where the JSON file and image assets will be stored.

This will allow us to enable picking image files from the NextCloud file browser.

When importing a recipe, any found images should be downloaded into the recipe folder.

**Comment by mrzapp** [comment]
@haeckle @Githopp192 @brogers-navex we can continue the discussion in this issue.

**Comment by mrzapp** [comment]
The change is in master now, but the app store is having some technical troubles, so I can't upload it for now.

**Comment by xsus95** [comment]
If I add a new recipe, then a link will be added under Image. But not the path where the image is copied locally. Does that mean that the image is still retrieved from the web?

![grafik](https://user-images.githubusercontent.com/55876457/66456057-d9071b80-ea6c-11e9-9599-4cd1932a1fdf.png)

**Comment by mrzapp** [comment]
@xsus95 the file is copied to your NextCloud, it's only ever retrieved from the "image" URL ahain if that file is deleted. It will be in your /Recipes/(recipe name) folder.
