### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#67]
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "cookbook.page.index" as such route does not exist.

    /var/www/nextcloud/lib/private/Route/Router.php - line 337:

    Symfony\Component\Routing\Generator\UrlGenerator->generate("cookbook.page.index", [], 1)

    /var/www/nextcloud/lib/private/Route/CachingRouter.php - line 60:

    OC\Route\Router->generate("cookbook.page.index", [], false)

    /var/www/nextcloud/lib/private/URLGenerator.php - line 79:

    OC\Route\CachingRouter->generate("cookbook.page.index", [])

    /var/www/nextcloud/lib/private/NavigationManager.php - line 292:

    OC\URLGenerator->linkToRoute("cookbook.page.index")

    /var/www/nextcloud/lib/private/NavigationManager.php - line 113:

    OC\NavigationManager->init()

    /var/www/nextcloud/apps/theming/lib/ThemingDefaults.php - line 179:

    OC\NavigationManager->getAll("guest")

    /var/www/nextcloud/lib/private/legacy/defaults.php - line 259:

    OCA\Theming\ThemingDefaults->getShortFooter()

    /var/www/nextcloud/lib/public/Defaults.php - line 167:

    OC_Defaults->getLongFooter()

    /var/www/nextcloud/core/templates/layout.guest.php - line 55:

    OCP\Defaults->getLongFooter()

    /var/www/nextcloud/lib/private/Template/Base.php - line 178:

    include("/var/www/ne ... p")

    /var/www/nextcloud/lib/private/Template/Base.php - line 150:

    OC\Template\Base->load("/var/www/ne ... p", null)

    /var/www/nextcloud/lib/private/legacy/template.php - line 180:

    OC\Template\Base->fetchPage(null)

    /var/www/nextcloud/lib/private/legacy/template.php - line 211:

    OC_Template->fetchPage(null)

    /var/www/nextcloud/lib/private/Template/Base.php - line 131:

    OC_Template->fetchPage()

    /var/www/nextcloud/lib/private/legacy/template.php - line 299:

    OC\Template\Base->printPage()

    /var/www/nextcloud/remote.php - line 80:

    OC_Template::printErrorPage("App not installed: ", "", 0)

    /var/www/nextcloud/remote.php - line 166:

    handleException(RemoteException {})

**Comment by mrzapp** [comment]
When exactly are you seeing this error? The "index" method does indeed exist in the PageController, and it's rendering, so I'm not sure what this error is for.

**Comment by xsus95** [comment]
I can not explain when the error occurs. It is also the first and so far only time. My assumption was that it appeared through the automatic update interval - but that does not fit in time.

**Comment by mrzapp** [comment]
Closing this issue as unreproducible, we can always reopen it if needed
