### ISSUE TITLE
Error: Call to undefined method OC\Files\Node\File::get()

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#68]
After update to version 0.5.0 i always got those errors:

![grafik](https://user-images.githubusercontent.com/55876457/66377701-676a9700-e9b2-11e9-8f48-f2165bdabf5f.png)

I have currently 3 recipes deposited. So I get an error per recipe.

**Comment by mrzapp** [comment]
This error should go away as soon as you rescan the library. It happens automatically after 5 minutes too

**Comment by xsus95** [comment]
Ok, to wait 5 minutes does not help. But after manually rescan it is perfect :-)

**Comment by mrzapp** [comment]
Or, I should say, wait 5 minutes and then reload the page :) This hiccup happened because of the new file structure required by the local images feature.

**Comment by xsus95** [comment]
mhh ... I had reopened the app after several minutes. The error still cropped up. it works only after the manual rescan - anyway. it's great now :-)
