### ISSUE TITLE
Wrong displaying of preparation and cook time

### ISSUE THREAD

**Issue by Scoon1e** [mrzapp/nextcloud-cookbook#69]
Hi there!

Seems to be just a little bug. If the preparation time is exactly 1h, then the last zero will be cut at the end. Maybe this happens also with the cook time. You can see the bug in the attached screenshot.

Kind regards!

![2019-10-08 18_24_02-Window](https://user-images.githubusercontent.com/56313967/66414289-64df6000-e9f9-11e9-8e3d-5413c6d904a4.png)

**Comment by mrzapp** [comment]
@sir-indy Is this one of yours? :)

**Comment by sir-indy** [comment]
Yes, I'll look into this. I think it's just a formatting oversight from me.

Note to self: See https://www.php.net/sprintf example 4.

**Comment by mrzapp** [comment]
@sir-indy great, thanks! You can just commit the change to the "develop" branch when you have time :)
