### ISSUE TITLE
Error in Recipedb.php

### ISSUE THREAD

**Issue by poltrian** [mrzapp/nextcloud-cookbook#7]
Hello,

i got these error, cookbooks works well but ite showing in the log file
Array to string conversion at /var/www/ubuntuone.ddns.net/html/nextcloud/apps/cookbook/lib/Db/RecipeDb.php#77

How can i fix it?

Thanks

Greetings

Olaf

**Comment by mrzapp** [comment]
@poltrian hmm, I'm having a hard time figuring out why the array would be converted to a string on that particular line. Can you try to var_dump($result) and paste the output here?
