### ISSUE TITLE
Keywords not handled consistently

### ISSUE THREAD

**Issue by dmbreakey** [mrzapp/nextcloud-cookbook#74]
When creating a recipe, the UI clearly indicates that the list of keywords are "comma-separated". However, when actually entering keywords, they are clearly parsed based on whitespace (at least, spaces) and commas, instead of just commas.

This makes using keywords like "Instant Pot" impossible, as it is parsed into "instant" and "pot".

I feel that keyword processing should be minimal: break up the list on commas, then trim excess whitespace (trim leading and trailing whitespace and *maybe* also collapse whitespace inside the tag to just one space). As for normalizing to lower-case, I have no opinion, but I imagine it's more useful than not, assuming it isn't required by the schema?

Or are there plans to integrate into NextCloud's native tagging mechanism? Is that even possible given the Schema.org framework?

**Comment by mrzapp** [comment]
Actually, @dmbreakey, would you be interested in contributing this change yourself, or should I handle it? The relevant code is [here](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/lib/Service/RecipeService.php#L138), if you're interested.

**Comment by dmbreakey** [comment]
Happy to do it but not familiar with actually using Git (beyond checking out code); do you want me to just paste the diff into this thread, then?

**Comment by dmbreakey** [comment]
Tested on my local install and it seems to work beautifully.

**Comment by theonlytruth** [comment]
My opinion about lower case keywords is the following: For Germans it looks very ugly if you have a list of keywords or categories and the are all written lower case. So if there are no technical problems with upper case keyword please make them possible.

**Comment by mrzapp** [comment]
@theonlytruth agreed, let's keep uppercase

**Comment by dmbreakey** [comment]
OK, already adjusted my local copy; how do I push it up?

**Comment by mrzapp** [comment]
@dmbreakey Sorry, I missed that last message of yours. I've done some work on this task too, but I'd like to see what you came up with :) Just do a [pull request](https://help.github.com/en/articles/creating-a-pull-request)

**Comment by dmbreakey** [comment]
OK; I'll try and do that tonight. I went a bit further than you did, and I think it will satisfactorily handle some corner cases that could otherwise be missed, although I'm not sure if these details are being handled elsewhere before they get here.

**Comment by dmbreakey** [comment]
Not sure I'm doing this correctly; attempted to follow the instructions [here](https://medium.com/@jonathanmines/the-ultimate-github-collaboration-guide-df816e98fb67), to create a new branch, and the push the edits to that branch but get a "Denied" response when I try to push it. Am I doing something incorrectly?

**Comment by mrzapp** [comment]
@dmbreakey I'm just guessing here, but that might be because you're trying to push to this repo directly. Step 1 is to create your own fork of this repo, which you might have overlooked.

**Comment by dmbreakey** [comment]
Sigh; I must be going blind. I could **swear** that wasn't there.

Forked now and I'll push the update tonight. Sorry about that.

**Comment by dmbreakey** [comment]
Sorry for the delay and thank you; doing this has forced me to get a much better understanding of how Git works. Plus I think I really like my editor.
