### ISSUE TITLE
rehost picture

### ISSUE THREAD

**Issue by quamok** [mrzapp/nextcloud-cookbook#83]
A great thing would be for the script to rehost recipe pictures to your nextcloud account, share it and create an hyperlink which would be added to the recipe.

this would prevent recipes from losing pictures when/if the recipe page ever get deleted/site goes down.

**Comment by theonlytruth** [comment]
The recipe pictures are automatically added to your Nextcloud recipes folder as full image and as thumbnail.

**Comment by christianlupus** [comment]
I think this issue is already solved as the data is locally copied since #64. So I will close this issue now.

If you had something else in mind, please describe a bit more verbosely and we can of course reopen it.

Thanks for reporting!

**Comment by quamok** [comment]
perfect, so if I understand correctly if the picture on the website where the recipe what fetched from isn't available/was deleted, Cookbook will default back to the picture in the local nextcloud recipe folder?
