### ISSUE TITLE
Carry over time fields

### ISSUE THREAD

**Issue by Timvde** [mrzapp/nextcloud-cookbook#95]
I encountered a recipe that had `PT70M` as its time field. This shows as 0:70 in Cookbook. It would be nice if it could be parsed and shown as 1:10 instead.

This issue and a workaround is mentioned in https://www.php.net/manual/en/class.dateinterval.php#102930

The major question is probably whether it should be done at import time or at viewing time. The first would make the internal json more correct, the latter would work for existing recipes.

**Comment by mrzapp** [comment]
@sir-indy This is probably related to #69, no?

**Comment by Timvde** [comment]
Not really. #69 is about not 0-padding up to two digits here: `$prep_mins = $prep_interval->format('%i');`. This issue would entail manipulating the `$prep_interval` before getting the minutes from it.

**Comment by mrzapp** [comment]
@Timvde maybe not related directly, but the fix would take place in the same portion of the code, namely [here](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/lib/Service/RecipeService.php#L72) and [here](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/templates/content/recipe.php#L21).

If you've got ideas, you're very welcome to submit a pull request, too :)

**Comment by Timvde** [comment]
It depends on the question I asked originally: where do you want to do it? I can think of arguments for both. So I could add it at both places if you think that's appropriate.

Fixing #69 looks trivial given https://www.php.net/manual/en/dateinterval.format.php, just use `%I` instead of `%i' :)

**Comment by mrzapp** [comment]
@Timvde in the [RecipeService::validateDuration method](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/lib/Service/RecipeService.php#L72), we should ensure that the format is ISO 8601, so that it will appear that way in the JSON.

Only when rendering the duration in the [template](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/templates/content/recipe.php#L21) should we present it as HH:MM

**Comment by Timvde** [comment]
Yes, that's true. But if I only change it in `validateDuration`, existing durations will still show wrong iiuc. I'm not sure if that's bad. But it would definitely be nicer if it's correct in the json that gets saved too.

**Comment by mrzapp** [comment]
@timvde I suggest enhancing the `validateDuration` method to parse other time formats to ISO 8601, for instance:

* `1:25` => `PT1H25M`
* `45` => `PT0H45M`

And anything containing language specific strings such as "close to 1 hour and about 23-36 minutes, maybe", we just scrap those.

That way, the JSON will always be correct, and existing durations will show up fine.

**Comment by Timvde** [comment]
Something like this then? https://regex101.com/r/rbK0oI/1

Do we also support seconds (should be an easy extension, although it might make `1:25` ambiguous...)?

**Comment by mrzapp** [comment]
@Timvde looks suitable to me. Let's not bother wiyh seconds for now :)

**Comment by mrzapp** [comment]
The solution to this issue actually didn't solve the initial request, but #111 will handle it instead, so closing this.
